export type LibraryCard = {
  it: string;
  en: string;
  example: string;
  tag: string;
  level: "A1" | "A2" | "B1" | "B2";
};

export const MISSION_TOPUP_PATCHES: Record<string, Partial<LibraryCard>> = {
  "il bagno": { example: "Il bagno e privato oppure condiviso?" },
  "la cucina": { example: "La cucina e condivisa con un altro inquilino." },
  "la visita": {
    en: "the apartment viewing",
    example: "Possiamo fissare una visita per domani pomeriggio?",
  },
  "l'appartamento": { example: "L'appartamento e vicino alla metro." },
  "la stanza": { example: "La stanza e piccola ma luminosa." },
  "il contratto": { example: "Il contratto inizia a maggio." },
  "le spese": {
    en: "the extra monthly costs",
    example: "Le spese mensili sono incluse nell'affitto?",
  },
  "il deposito": {
    it: "il deposito cauzionale",
    en: "the security deposit",
    example: "Il deposito cauzionale corrisponde a due mensilità.",
  },
  "la data di ingresso": {
    it: "la data di disponibilità",
    en: "the move-in date",
    example: "Qual è la data di disponibilità dell'appartamento?",
  },
  "il proprietario": { example: "Il proprietario vive in citta." },
  "incluso": { example: "Il wifi e incluso nel prezzo?" },
  "il trasloco": { example: "Il trasloco e previsto per lunedi." },
  "l'agenzia": { example: "L'agenzia chiede una commissione." },
  "l'annuncio": { example: "Ho visto il suo annuncio online." },
  "il problema": { example: "C'e un problema con il contratto?" },
  "la soluzione": { example: "Cerchiamo una soluzione semplice." },
  "l'obiettivo": { example: "Il mio obiettivo e entrare entro fine mese." },
  "il dettaglio": { example: "Mi manda un dettaglio in piu sulle spese?" },
  "la conferma": {
    en: "the confirmation",
    example: "Aspetto la conferma della visita per email.",
  },
  "la decisione": { example: "Le faccio sapere la mia decisione domani." },
  "il soggiorno": { example: "Il soggiorno e gia arredato." },
};

export const SEED_CARD_PATCHES: Array<{ matchIt: string; changes: Partial<LibraryCard> }> = [
  { matchIt: "ciao", changes: { en: "hello", example: "Ciao, come stai?" } },
  { matchIt: "mi chiamo...", changes: { it: "mi chiamo", en: "my name is", example: "Mi chiamo Luca." } },
  {
    matchIt: "sono allergico/a a...",
    changes: { it: "sono allergico a", en: "I am allergic to", example: "Sono allergico alle noccioline." },
  },
  {
    matchIt: "il primo / il secondo",
    changes: { it: "il primo piatto", en: "the first course", example: "Come primo piatto prendo la pasta." },
  },
  {
    matchIt: "avere fame / sete",
    changes: { it: "avere fame", en: "to be hungry", example: "Ho fame, andiamo a mangiare?" },
  },
  {
    matchIt: "il/la partner",
    changes: { it: "il partner", en: "the partner", example: "Il mio partner lavora a Milano." },
  },
  {
    matchIt: "assaggiare",
    changes: { en: "to taste", example: "Vuoi assaggiare il mio tiramisu?" },
  },
  {
    matchIt: "magari",
    changes: { en: "if only", example: "Magari fossi gia in vacanza." },
  },
  {
    matchIt: "piuttosto",
    changes: { en: "rather", example: "Preferisco restare a casa, piuttosto." },
  },
  {
    matchIt: "figurati",
    changes: { en: "don't mention it", example: "Grazie per l'aiuto. Figurati." },
  },
  {
    matchIt: "il portafoglio",
    changes: { en: "the wallet", example: "Ho lasciato il portafoglio sul tavolo." },
  },
  {
    matchIt: "la pratica",
    changes: { en: "the application file", example: "La pratica per il permesso e ancora in lavorazione." },
  },
  {
    matchIt: "il documento",
    changes: { en: "the document", example: "Mi manca ancora un documento per la domanda." },
  },
  {
    matchIt: "sbattere",
    changes: { en: "to slam", example: "Non sbattere la porta, per favore." },
  },
];

export const SEED_CARD_INSERTS: LibraryCard[] = [
  { it: "avere sete", en: "to be thirsty", example: "Dopo il viaggio ho molta sete.", tag: "food", level: "A2" },
  { it: "il secondo piatto", en: "the second course", example: "Come secondo piatto prendo il pesce.", tag: "food", level: "A2" },
  { it: "il cameriere", en: "waiter", example: "Il cameriere ci porta il menu.", tag: "professioni", level: "A2" },
  { it: "lavorare", en: "to work", example: "Lavoro in ufficio dal lunedi al venerdi.", tag: "professioni", level: "A2" },
  { it: "l'ufficio", en: "office", example: "Il mio ufficio e in centro.", tag: "professioni", level: "A2" },
  { it: "la partner", en: "the partner", example: "La mia partner arriva piu tardi.", tag: "emotions", level: "B1" },
  { it: "magari no", en: "maybe not", example: "Usciamo stasera? Magari no, sono stanco.", tag: "connectors", level: "B2" },
  { it: "piuttosto che", en: "rather than", example: "Prendo il treno piuttosto che la macchina.", tag: "connectors", level: "B2" },
  { it: "figurati che", en: "just imagine", example: "Figurati che ho perso l'ultimo treno.", tag: "idioms", level: "B2" },
  { it: "il portafoglio titoli", en: "the investment portfolio", example: "Il portafoglio titoli e ben diversificato.", tag: "finance", level: "B2" },
  { it: "la pratica burocratica", en: "the paperwork file", example: "La pratica burocratica richiede ancora due firme.", tag: "bureaucracy", level: "B2" },
  { it: "sbattersi", en: "to bust one's ass", example: "Mi sono sbattuto tutto il giorno per chiudere il progetto.", tag: "slang", level: "B2" },
];

export const A1_AUDIT_EXPANSION: LibraryCard[] = [
  { it: "cerco una stanza singola", en: "I am looking for a single room", example: "Cerco una stanza singola vicino alla metro.", tag: "home", level: "A1" },
  { it: "l'affitto e trattabile", en: "the rent is negotiable", example: "L'affitto e trattabile o e fisso?", tag: "home", level: "A1" },
  { it: "quanto costa al mese", en: "how much is it per month", example: "Quanto costa al mese questa stanza?", tag: "home", level: "A1" },
  { it: "la stanza e arredata", en: "the room is furnished", example: "La stanza e arredata oppure no?", tag: "home", level: "A1" },
  { it: "e una stanza doppia", en: "it is a double room", example: "No, non e singola: e una stanza doppia.", tag: "home", level: "A1" },
  { it: "cerco un monolocale", en: "I am looking for a studio apartment", example: "Cerco un monolocale non troppo lontano dal centro.", tag: "home", level: "A1" },
  { it: "la cucina e condivisa", en: "the kitchen is shared", example: "La cucina e condivisa con altri due studenti.", tag: "home", level: "A1" },
  { it: "il bagno e privato", en: "the bathroom is private", example: "Il bagno e privato oppure condiviso?", tag: "home", level: "A1" },
  { it: "la stanza e libera da subito", en: "the room is available immediately", example: "La stanza e libera da subito.", tag: "home", level: "A1" },
  { it: "vorrei vedere l'appartamento", en: "I would like to see the apartment", example: "Vorrei vedere l'appartamento domani.", tag: "home", level: "A1" },
  { it: "a che piano si trova", en: "what floor is it on", example: "A che piano si trova l'appartamento?", tag: "home", level: "A1" },
  { it: "c'e l'ascensore", en: "is there a lift", example: "C'e l'ascensore nel palazzo?", tag: "home", level: "A1" },
  { it: "quanto dura il contratto", en: "how long is the contract", example: "Quanto dura il contratto di affitto?", tag: "home", level: "A1" },
  { it: "posso prendere le misure", en: "can I take the measurements", example: "Posso prendere le misure della stanza?", tag: "home", level: "A1" },
  { it: "quando posso entrare", en: "when can I move in", example: "Quando posso entrare nell'appartamento?", tag: "home", level: "A1" },
  { it: "la zona e tranquilla", en: "the area is quiet", example: "La zona e tranquilla la sera.", tag: "home", level: "A1" },
  { it: "e vicino alla metro", en: "it is near the metro", example: "Si, e vicino alla metro.", tag: "home", level: "A1" },
  { it: "mi serve un posto letto", en: "I need a bed space", example: "Per ora mi serve solo un posto letto.", tag: "home", level: "A1" },
  { it: "posso lasciare una caparra", en: "can I leave a deposit", example: "Posso lasciare una caparra oggi?", tag: "home", level: "A1" },
  { it: "la stanza da sulla strada", en: "the room faces the street", example: "La stanza da sulla strada principale.", tag: "home", level: "A1" },

  { it: "avete un tavolo libero", en: "do you have a free table", example: "Buonasera, avete un tavolo libero?", tag: "food", level: "A1" },
  { it: "abbiamo una prenotazione", en: "we have a reservation", example: "Abbiamo una prenotazione per le otto.", tag: "food", level: "A1" },
  { it: "preferisco stare dentro", en: "I prefer to sit inside", example: "Stasera preferisco stare dentro.", tag: "food", level: "A1" },
  { it: "vorrei ordinare", en: "I would like to order", example: "Vorrei ordinare adesso, grazie.", tag: "food", level: "A1" },
  { it: "per me la pasta", en: "for me, the pasta", example: "Per me la pasta al pomodoro.", tag: "food", level: "A1" },
  { it: "senza formaggio", en: "without cheese", example: "Per me la pasta senza formaggio.", tag: "food", level: "A1" },
  { it: "che cosa consiglia", en: "what do you recommend", example: "Che cosa consiglia oggi?", tag: "food", level: "A1" },
  { it: "e troppo salato", en: "it is too salty", example: "Mi dispiace, per me e troppo salato.", tag: "food", level: "A1" },
  { it: "potrebbe portarci del pane", en: "could you bring us some bread", example: "Potrebbe portarci del pane, per favore?", tag: "food", level: "A1" },
  { it: "dividiamo un antipasto", en: "we are sharing an appetizer", example: "Dividiamo un antipasto e poi prendiamo due primi.", tag: "food", level: "A1" },
  { it: "offro io", en: "it is on me", example: "Stasera offro io.", tag: "social", level: "A1" },
  { it: "che buona idea", en: "what a good idea", example: "Un aperitivo prima di cena? Che buona idea.", tag: "social", level: "A1" },
  { it: "arrivo tra dieci minuti", en: "I am arriving in ten minutes", example: "Scusa il ritardo, arrivo tra dieci minuti.", tag: "social", level: "A1" },
  { it: "ti aspetto fuori", en: "I will wait for you outside", example: "Ti aspetto fuori dal ristorante.", tag: "social", level: "A1" },
  { it: "grazie per l'invito", en: "thanks for the invitation", example: "Grazie per l'invito a cena.", tag: "social", level: "A1" },
  { it: "complimenti, e buonissimo", en: "compliments, it is delicious", example: "Complimenti, e buonissimo questo risotto.", tag: "social", level: "A1" },

  { it: "a che ora parte", en: "what time does it leave", example: "A che ora parte il prossimo treno?", tag: "travel", level: "A1" },
  { it: "da quale binario", en: "from which platform", example: "Da quale binario parte il regionale?", tag: "travel", level: "A1" },
  { it: "ho perso il treno", en: "I missed the train", example: "Scusi, ho perso il treno per Bologna.", tag: "travel", level: "A1" },
  { it: "il treno e cancellato", en: "the train is cancelled", example: "Il treno delle nove e cancellato.", tag: "travel", level: "A1" },
  { it: "devo cambiare a Firenze", en: "I have to change in Florence", example: "Devo cambiare a Firenze o vado diretto?", tag: "travel", level: "A1" },
  { it: "c'e un treno piu tardi", en: "is there a later train", example: "C'e un treno piu tardi per Roma?", tag: "travel", level: "A1" },
  { it: "vorrei cambiare il biglietto", en: "I would like to change the ticket", example: "Vorrei cambiare il biglietto per domani.", tag: "travel", level: "A1" },
  { it: "devo timbrare il biglietto", en: "do I need to validate the ticket", example: "Scusi, devo timbrare il biglietto?", tag: "travel", level: "A1" },
  { it: "c'e uno sciopero oggi", en: "there is a strike today", example: "Mi hanno detto che c'e uno sciopero oggi.", tag: "travel", level: "A1" },
  { it: "questa e la fermata giusta", en: "this is the right stop", example: "Scusi, questa e la fermata giusta?", tag: "travel", level: "A1" },
  { it: "devo prendere il regionale", en: "I need to take the regional train", example: "Per Pisa devo prendere il regionale?", tag: "travel", level: "A1" },
  { it: "quanto tempo ci vuole", en: "how long does it take", example: "Quanto tempo ci vuole fino a Milano?", tag: "travel", level: "A1" },
  { it: "il posto e occupato", en: "the seat is taken", example: "Mi scusi, questo posto e occupato?", tag: "travel", level: "A1" },
  { it: "il controllore arriva", en: "the ticket inspector is coming", example: "Prepara il biglietto, il controllore arriva.", tag: "travel", level: "A1" },
  { it: "scendo alla prossima", en: "I am getting off at the next stop", example: "No grazie, scendo alla prossima.", tag: "travel", level: "A1" },
  { it: "mi puo indicare l'uscita", en: "can you show me the exit", example: "Mi puo indicare l'uscita per i taxi?", tag: "travel", level: "A1" },

  { it: "mi fa male la gola", en: "my throat hurts", example: "Da ieri mi fa male la gola.", tag: "health", level: "A1" },
  { it: "ho la tosse", en: "I have a cough", example: "Buonasera, ho la tosse da due giorni.", tag: "health", level: "A1" },
  { it: "ho mal di stomaco", en: "I have a stomach ache", example: "Dopo pranzo ho mal di stomaco.", tag: "health", level: "A1" },
  { it: "da quanto tempo", en: "for how long", example: "Da quanto tempo hai la febbre?", tag: "health", level: "A1" },
  { it: "ha qualcosa per la febbre", en: "do you have something for a fever", example: "Ha qualcosa per la febbre?", tag: "health", level: "A1" },
  { it: "devo prendere una compressa", en: "I need to take one tablet", example: "Devo prendere una compressa dopo cena?", tag: "health", level: "A1" },
  { it: "prima o dopo i pasti", en: "before or after meals", example: "Questa medicina si prende prima o dopo i pasti?", tag: "health", level: "A1" },
  { it: "sono intollerante al lattosio", en: "I am lactose intolerant", example: "Sono intollerante al lattosio.", tag: "health", level: "A1" },
  { it: "mi gira la testa", en: "I feel dizzy", example: "Da stamattina mi gira la testa.", tag: "health", level: "A1" },
  { it: "devo riposare", en: "I need to rest", example: "Oggi devo riposare tutto il giorno.", tag: "health", level: "A1" },
  { it: "ha bisogno della ricetta", en: "do you need a prescription", example: "Per questo farmaco ha bisogno della ricetta?", tag: "health", level: "A1" },
  { it: "quante volte al giorno", en: "how many times a day", example: "Quante volte al giorno devo prenderlo?", tag: "health", level: "A1" },
  { it: "non mi sento bene", en: "I do not feel well", example: "Oggi non mi sento bene.", tag: "health", level: "A1" },
  { it: "mi serve una farmacia di turno", en: "I need a pharmacy on duty", example: "Mi serve una farmacia di turno qui vicino.", tag: "health", level: "A1" },

  { it: "sono in ritardo di cinque minuti", en: "I am five minutes late", example: "Scusa, sono in ritardo di cinque minuti.", tag: "time", level: "A1" },
  { it: "ci vediamo verso le sette", en: "let's meet around seven", example: "Ci vediamo verso le sette davanti al bar.", tag: "time", level: "A1" },
  { it: "sono libero domani mattina", en: "I am free tomorrow morning", example: "Sono libero domani mattina dalle nove.", tag: "time", level: "A1" },
  { it: "oggi non posso", en: "I cannot today", example: "Oggi non posso, ho gia un impegno.", tag: "time", level: "A1" },
  { it: "rimandiamo a domani", en: "let's postpone it until tomorrow", example: "Sei stanco? Rimandiamo a domani.", tag: "time", level: "A1" },
  { it: "lavoro fino alle sei", en: "I work until six", example: "Oggi lavoro fino alle sei.", tag: "time", level: "A1" },
  { it: "faccio pausa alle due", en: "I take a break at two", example: "Di solito faccio pausa alle due.", tag: "time", level: "A1" },
  { it: "di solito esco presto", en: "I usually leave early", example: "Il venerdi di solito esco presto.", tag: "time", level: "A1" },
  { it: "ho un appuntamento alle tre", en: "I have an appointment at three", example: "Domani ho un appuntamento alle tre.", tag: "time", level: "A1" },
  { it: "torno a casa tardi", en: "I get home late", example: "Il martedi torno a casa tardi.", tag: "time", level: "A1" },
  { it: "mi sveglio alle sette", en: "I wake up at seven", example: "Nei giorni feriali mi sveglio alle sette.", tag: "routine", level: "A1" },
  { it: "faccio la doccia la mattina", en: "I shower in the morning", example: "Di solito faccio la doccia la mattina.", tag: "routine", level: "A1" },

  { it: "come si dice in italiano", en: "how do you say it in Italian", example: "Scusi, come si dice in italiano?", tag: "basics", level: "A1" },
  { it: "come si scrive", en: "how do you spell it", example: "Come si scrive il suo cognome?", tag: "basics", level: "A1" },
  { it: "puo parlare piu piano", en: "can you speak more slowly", example: "Mi scusi, puo parlare piu piano?", tag: "basics", level: "A1" },
  { it: "non ho capito bene", en: "I did not understand well", example: "Mi dispiace, non ho capito bene.", tag: "basics", level: "A1" },
  { it: "puo scriverlo", en: "can you write it down", example: "Puo scriverlo su un foglio?", tag: "basics", level: "A1" },
  { it: "puo mostrarmelo", en: "can you show it to me", example: "Non capisco: puo mostrarmelo?", tag: "basics", level: "A1" },
  { it: "un attimo, per favore", en: "one moment, please", example: "Un attimo, per favore, cerco il portafoglio.", tag: "basics", level: "A1" },
  { it: "va bene cosi", en: "that is fine like that", example: "Si, va bene cosi, grazie.", tag: "basics", level: "A1" },
  { it: "non ne sono sicuro", en: "I am not sure", example: "Non ne sono sicuro, controllo subito.", tag: "basics", level: "A1" },
  { it: "puo aspettare un momento", en: "can you wait a moment", example: "Puo aspettare un momento, per favore?", tag: "basics", level: "A1" },
  { it: "ho bisogno di piu tempo", en: "I need more time", example: "Ho bisogno di piu tempo per decidere.", tag: "basics", level: "A1" },
  { it: "puo ripetere l'ultima frase", en: "can you repeat the last sentence", example: "Puo ripetere l'ultima frase, per favore?", tag: "basics", level: "A1" },
  { it: "sto ancora imparando", en: "I am still learning", example: "Parli pure piano, sto ancora imparando.", tag: "basics", level: "A1" },
  { it: "mi puo aiutare", en: "can you help me", example: "Mi puo aiutare con il modulo?", tag: "basics", level: "A1" },
];

// Sized to add roughly +154 A2 live rows and +204 B1 live rows via bidirectional inserts.
export const A2_AUDIT_EXPANSION: LibraryCard[] = [
  { it: "sono", en: "I am", example: "Sono italiano.", tag: "presentarsi", level: "A2" },
  { it: "piacere", en: "nice to meet you", example: "Piacere, mi chiamo Anna.", tag: "presentarsi", level: "A2" },
  { it: "di dove sei?", en: "where are you from?", example: "Di dove sei? Sono di Roma.", tag: "presentarsi", level: "A2" },
  { it: "abito a", en: "I live in", example: "Abito a Milano.", tag: "presentarsi", level: "A2" },
  { it: "ho ... anni", en: "I am ... years old", example: "Ho venticinque anni.", tag: "presentarsi", level: "A2" },
  { it: "vengo da", en: "I come from", example: "Vengo da Londra.", tag: "presentarsi", level: "A2" },
  { it: "come stai?", en: "how are you?", example: "Ciao, come stai?", tag: "presentarsi", level: "A2" },
  { it: "bene, grazie", en: "fine, thanks", example: "Sto bene, grazie.", tag: "presentarsi", level: "A2" },
  { it: "e tu?", en: "and you?", example: "Io sto bene, e tu?", tag: "presentarsi", level: "A2" },
  { it: "la madre", en: "mother", example: "Mia madre si chiama Maria.", tag: "famiglia", level: "A2" },
  { it: "il padre", en: "father", example: "Mio padre lavora in banca.", tag: "famiglia", level: "A2" },
  { it: "il fratello", en: "brother", example: "Ho un fratello maggiore.", tag: "famiglia", level: "A2" },
  { it: "la sorella", en: "sister", example: "Mia sorella ha vent'anni.", tag: "famiglia", level: "A2" },
  { it: "i nonni", en: "grandparents", example: "I miei nonni vivono in campagna.", tag: "famiglia", level: "A2" },
  { it: "lo zio", en: "uncle", example: "Mio zio abita a Napoli.", tag: "famiglia", level: "A2" },
  { it: "la zia", en: "aunt", example: "La zia prepara la torta.", tag: "famiglia", level: "A2" },
  { it: "il cugino", en: "cousin (m)", example: "Il mio cugino è simpatico.", tag: "famiglia", level: "A2" },
  { it: "maggiore", en: "older", example: "Sono il fratello maggiore.", tag: "famiglia", level: "A2" },
  { it: "minore", en: "younger", example: "La sorella minore è a scuola.", tag: "famiglia", level: "A2" },
  { it: "quanti anni hai?", en: "how old are you?", example: "Quanti anni hai?", tag: "numeri-et", level: "A2" },
  { it: "venti", en: "twenty", example: "Ho venti anni.", tag: "numeri-et", level: "A2" },
  { it: "trenta", en: "thirty", example: "Mio fratello ha trent'anni.", tag: "numeri-et", level: "A2" },
  { it: "quaranta", en: "forty", example: "Mia madre ha quarant'anni.", tag: "numeri-et", level: "A2" },
  { it: "cento", en: "one hundred", example: "La nonna ha quasi cento anni.", tag: "numeri-et", level: "A2" },
  { it: "il numero", en: "number", example: "Qual è il tuo numero di telefono?", tag: "numeri-et", level: "A2" },
  { it: "il compleanno", en: "birthday", example: "Il mio compleanno è in maggio.", tag: "numeri-et", level: "A2" },
  { it: "primo", en: "first", example: "È il mio primo giorno.", tag: "numeri-et", level: "A2" },
  { it: "secondo", en: "second", example: "Abito al secondo piano.", tag: "numeri-et", level: "A2" },
  { it: "rosso", en: "red", example: "La macchina rossa è bella.", tag: "colori-descrizioni", level: "A2" },
  { it: "blu", en: "blue", example: "Il cielo è blu.", tag: "colori-descrizioni", level: "A2" },
  { it: "verde", en: "green", example: "Mi piace la maglietta verde.", tag: "colori-descrizioni", level: "A2" },
  { it: "grande", en: "big", example: "La casa è grande.", tag: "colori-descrizioni", level: "A2" },
  { it: "piccolo", en: "small", example: "Ho un cane piccolo.", tag: "colori-descrizioni", level: "A2" },
  { it: "bello", en: "beautiful", example: "Che bel vestito!", tag: "colori-descrizioni", level: "A2" },
  { it: "brutto", en: "ugly", example: "Il tempo è brutto oggi.", tag: "colori-descrizioni", level: "A2" },
  { it: "nuovo", en: "new", example: "Ho comprato un telefono nuovo.", tag: "colori-descrizioni", level: "A2" },
  { it: "vecchio", en: "old", example: "Questa chiesa è molto vecchia.", tag: "colori-descrizioni", level: "A2" },
  { it: "chiaro", en: "light (color)", example: "Preferisco il verde chiaro.", tag: "colori-descrizioni", level: "A2" },
  { it: "la pizza", en: "pizza", example: "Vorrei una pizza margherita.", tag: "cibo-bevande", level: "A2" },
  { it: "la pasta", en: "pasta", example: "La pasta è al dente.", tag: "cibo-bevande", level: "A2" },
  { it: "il caffè", en: "coffee", example: "Prendo un caffè, grazie.", tag: "cibo-bevande", level: "A2" },
  { it: "l'acqua", en: "water", example: "Un'acqua naturale, per favore.", tag: "cibo-bevande", level: "A2" },
  { it: "il vino", en: "wine", example: "Un bicchiere di vino rosso.", tag: "cibo-bevande", level: "A2" },
  { it: "il pane", en: "bread", example: "Vorrei del pane fresco.", tag: "cibo-bevande", level: "A2" },
  { it: "il formaggio", en: "cheese", example: "Il parmigiano è delizioso.", tag: "cibo-bevande", level: "A2" },
  { it: "la carne", en: "meat", example: "Non mangio la carne.", tag: "cibo-bevande", level: "A2" },
  { it: "la verdura", en: "vegetables", example: "Mangio molta verdura.", tag: "cibo-bevande", level: "A2" },
  { it: "il dolce", en: "dessert", example: "Come dolce prendo il tiramisù.", tag: "cibo-bevande", level: "A2" },
  { it: "la cucina", en: "kitchen", example: "La cucina è grande.", tag: "casa", level: "A2" },
  { it: "il bagno", en: "bathroom", example: "Il bagno è al primo piano.", tag: "casa", level: "A2" },
  { it: "la camera da letto", en: "bedroom", example: "La camera da letto è luminosa.", tag: "casa", level: "A2" },
  { it: "il salotto", en: "living room", example: "Guardiamo la TV in salotto.", tag: "casa", level: "A2" },
  { it: "il balcone", en: "balcony", example: "C'è un balcone con vista sul mare.", tag: "casa", level: "A2" },
  { it: "il tavolo", en: "table", example: "Il tavolo è in cucina.", tag: "casa", level: "A2" },
  { it: "la sedia", en: "chair", example: "Ci sono quattro sedie.", tag: "casa", level: "A2" },
  { it: "il divano", en: "sofa", example: "Mi siedo sul divano.", tag: "casa", level: "A2" },
  { it: "la finestra", en: "window", example: "Apri la finestra, per favore.", tag: "casa", level: "A2" },
  { it: "la maglietta", en: "t-shirt", example: "Questa maglietta è troppo grande.", tag: "vestiti", level: "A2" },
  { it: "i pantaloni", en: "trousers", example: "Quei pantaloni costano troppo.", tag: "vestiti", level: "A2" },
  { it: "le scarpe", en: "shoes", example: "Mi piacciono quelle scarpe.", tag: "vestiti", level: "A2" },
  { it: "la giacca", en: "jacket", example: "Ho bisogno di una giacca nuova.", tag: "vestiti", level: "A2" },
  { it: "il vestito", en: "dress/suit", example: "Che bel vestito!", tag: "vestiti", level: "A2" },
  { it: "stretto", en: "tight", example: "Questi pantaloni sono stretti.", tag: "vestiti", level: "A2" },
  { it: "largo", en: "loose/wide", example: "La giacca è troppo larga.", tag: "vestiti", level: "A2" },
  { it: "lunedì", en: "Monday", example: "Il lunedì vado in palestra.", tag: "giorni-mesi", level: "A2" },
  { it: "venerdì", en: "Friday", example: "Venerdì sera usciamo.", tag: "giorni-mesi", level: "A2" },
  { it: "il fine settimana", en: "weekend", example: "Cosa fai il fine settimana?", tag: "giorni-mesi", level: "A2" },
  { it: "gennaio", en: "January", example: "In gennaio fa freddo.", tag: "giorni-mesi", level: "A2" },
  { it: "agosto", en: "August", example: "In agosto andiamo al mare.", tag: "giorni-mesi", level: "A2" },
  { it: "la settimana", en: "week", example: "La prossima settimana ho un esame.", tag: "giorni-mesi", level: "A2" },
  { it: "il mese", en: "month", example: "Questo mese è corto.", tag: "giorni-mesi", level: "A2" },
  { it: "ieri", en: "yesterday", example: "Ieri ho lavorato tutto il giorno.", tag: "giorni-mesi", level: "A2" },
  { it: "il medico", en: "doctor", example: "Faccio il medico.", tag: "professioni", level: "A2" },
  { it: "l'insegnante", en: "teacher", example: "Mia madre fa l'insegnante.", tag: "professioni", level: "A2" },
  { it: "l'avvocato", en: "lawyer", example: "Mio zio è avvocato.", tag: "professioni", level: "A2" },
  { it: "l'ingegnere", en: "engineer", example: "Lavoro come ingegnere.", tag: "professioni", level: "A2" },
  { it: "il cuoco", en: "cook/chef", example: "Il cuoco è molto bravo.", tag: "professioni", level: "A2" },
];

export const B1_AUDIT_EXPANSION: LibraryCard[] = [
  { it: "ho mangiato", en: "I ate/have eaten", example: "Ho mangiato una pizza.", tag: "passato-prossimo", level: "B1" },
  { it: "sono andato", en: "I went/have gone", example: "Sono andato al cinema ieri.", tag: "passato-prossimo", level: "B1" },
  { it: "ho visto", en: "I saw/have seen", example: "Ho visto un bel film.", tag: "passato-prossimo", level: "B1" },
  { it: "sono partito", en: "I left/departed", example: "Sono partito stamattina.", tag: "passato-prossimo", level: "B1" },
  { it: "ho comprato", en: "I bought", example: "Ho comprato un regalo.", tag: "passato-prossimo", level: "B1" },
  { it: "sono tornato", en: "I came back", example: "Sono tornato a casa tardi.", tag: "passato-prossimo", level: "B1" },
  { it: "ho scritto", en: "I wrote", example: "Ho scritto un'email.", tag: "passato-prossimo", level: "B1" },
  { it: "sono rimasto", en: "I stayed", example: "Sono rimasto a casa.", tag: "passato-prossimo", level: "B1" },
  { it: "ho fatto", en: "I did/made", example: "Ho fatto i compiti.", tag: "passato-prossimo", level: "B1" },
  { it: "sono uscito", en: "I went out", example: "Sono uscito con gli amici.", tag: "passato-prossimo", level: "B1" },
  { it: "da bambino", en: "as a child", example: "Da bambino giocavo sempre fuori.", tag: "imperfetto", level: "B1" },
  { it: "andavo", en: "I used to go", example: "Andavo al mare ogni estate.", tag: "imperfetto", level: "B1" },
  { it: "era", en: "it was", example: "Era una giornata bellissima.", tag: "imperfetto", level: "B1" },
  { it: "faceva", en: "it was (weather)", example: "Faceva caldo quel giorno.", tag: "imperfetto", level: "B1" },
  { it: "c'era", en: "there was", example: "C'era un bel sole.", tag: "imperfetto", level: "B1" },
  { it: "mentre", en: "while", example: "Mentre mangiavo, è squillato il telefono.", tag: "imperfetto", level: "B1" },
  { it: "sempre", en: "always", example: "Studiavo sempre la sera.", tag: "imperfetto", level: "B1" },
  { it: "ogni", en: "every", example: "Ogni domenica pranzavamo dai nonni.", tag: "imperfetto", level: "B1" },
  { it: "vivevo", en: "I used to live", example: "Vivevo a Firenze.", tag: "imperfetto", level: "B1" },
  { it: "sembrava", en: "it seemed", example: "Sembrava un sogno.", tag: "imperfetto", level: "B1" },
  { it: "improvvisamente", en: "suddenly", example: "Improvvisamente ha iniziato a piovere.", tag: "passato-vs-imperfetto", level: "B1" },
  { it: "nel frattempo", en: "meanwhile", example: "Nel frattempo, io aspettavo.", tag: "passato-vs-imperfetto", level: "B1" },
  { it: "a un certo punto", en: "at a certain point", example: "A un certo punto è arrivata la polizia.", tag: "passato-vs-imperfetto", level: "B1" },
  { it: "già", en: "already", example: "Avevo già finito quando è arrivato.", tag: "passato-vs-imperfetto", level: "B1" },
  { it: "stavo per", en: "I was about to", example: "Stavo per uscire quando hai chiamato.", tag: "passato-vs-imperfetto", level: "B1" },
  { it: "all'improvviso", en: "all of a sudden", example: "All'improvviso si è spenta la luce.", tag: "passato-vs-imperfetto", level: "B1" },
  { it: "di solito", en: "usually", example: "Di solito prendevo il treno.", tag: "passato-vs-imperfetto", level: "B1" },
  { it: "quella volta", en: "that time", example: "Quella volta sono andato in macchina.", tag: "passato-vs-imperfetto", level: "B1" },
  { it: "succedere", en: "to happen", example: "Cosa è successo?", tag: "passato-vs-imperfetto", level: "B1" },
  { it: "raccontare", en: "to tell/narrate", example: "Ti racconto cosa è successo.", tag: "passato-vs-imperfetto", level: "B1" },
  { it: "andrò", en: "I will go", example: "Domani andrò al mare.", tag: "futuro", level: "B1" },
  { it: "farò", en: "I will do/make", example: "Farò una torta per la festa.", tag: "futuro", level: "B1" },
  { it: "sarà", en: "it will be", example: "Sarà una bella giornata.", tag: "futuro", level: "B1" },
  { it: "avrò", en: "I will have", example: "Avrò più tempo il mese prossimo.", tag: "futuro", level: "B1" },
  { it: "verrò", en: "I will come", example: "Verrò alla tua festa.", tag: "futuro", level: "B1" },
  { it: "potrò", en: "I will be able to", example: "Potrò aiutarti domani.", tag: "futuro", level: "B1" },
  { it: "dovrò", en: "I will have to", example: "Dovrò studiare di più.", tag: "futuro", level: "B1" },
  { it: "tra", en: "in (time)", example: "Tra due settimane vado in vacanza.", tag: "futuro", level: "B1" },
  { it: "il prossimo anno", en: "next year", example: "Il prossimo anno viaggerò di più.", tag: "futuro", level: "B1" },
  { it: "chissà", en: "who knows", example: "Chissà cosa succederà.", tag: "futuro", level: "B1" },
  { it: "il volo", en: "flight", example: "Il volo parte alle dieci.", tag: "viaggi", level: "B1" },
  { it: "la valigia", en: "suitcase", example: "Devo fare la valigia.", tag: "viaggi", level: "B1" },
  { it: "l'albergo", en: "hotel", example: "Ho prenotato un albergo in centro.", tag: "viaggi", level: "B1" },
  { it: "la prenotazione", en: "reservation", example: "Ho una prenotazione a nome Rossi.", tag: "viaggi", level: "B1" },
  { it: "il passaporto", en: "passport", example: "Non dimenticare il passaporto!", tag: "viaggi", level: "B1" },
  { it: "la cartina", en: "map", example: "Hai una cartina della città?", tag: "viaggi", level: "B1" },
  { it: "il check-in", en: "check-in", example: "Il check-in è alle tre.", tag: "viaggi", level: "B1" },
  { it: "l'escursione", en: "excursion", example: "Facciamo un'escursione domani.", tag: "viaggi", level: "B1" },
  { it: "il souvenir", en: "souvenir", example: "Ho comprato dei souvenir.", tag: "viaggi", level: "B1" },
  { it: "all'estero", en: "abroad", example: "Quest'estate vado all'estero.", tag: "viaggi", level: "B1" },
  { it: "più caro", en: "more expensive", example: "Questo è più caro di quello.", tag: "shopping-comparativi", level: "B1" },
  { it: "meno costoso", en: "less expensive", example: "La camicia è meno costosa.", tag: "shopping-comparativi", level: "B1" },
  { it: "migliore", en: "better", example: "Questa qualità è migliore.", tag: "shopping-comparativi", level: "B1" },
  { it: "peggiore", en: "worse", example: "Il servizio qui è peggiore.", tag: "shopping-comparativi", level: "B1" },
  { it: "il più bello", en: "the most beautiful", example: "È il vestito più bello.", tag: "shopping-comparativi", level: "B1" },
  { it: "conveniente", en: "affordable/good deal", example: "Questo negozio è conveniente.", tag: "shopping-comparativi", level: "B1" },
  { it: "la qualità", en: "quality", example: "La qualità è ottima.", tag: "shopping-comparativi", level: "B1" },
  { it: "il marchio", en: "brand", example: "Che marchio preferisci?", tag: "shopping-comparativi", level: "B1" },
  { it: "il cambio", en: "exchange/return", example: "Posso fare il cambio?", tag: "shopping-comparativi", level: "B1" },
  { it: "provarsi", en: "to try on (reflexive)", example: "Mi provo questa giacca.", tag: "shopping-comparativi", level: "B1" },
  { it: "la riunione", en: "meeting", example: "Ho una riunione alle dieci.", tag: "lavoro", level: "B1" },
  { it: "il capo", en: "boss", example: "Il capo vuole il report domani.", tag: "lavoro", level: "B1" },
  { it: "il progetto", en: "project", example: "Stiamo lavorando a un nuovo progetto.", tag: "lavoro", level: "B1" },
  { it: "il curriculum", en: "CV/resume", example: "Ho mandato il mio curriculum.", tag: "lavoro", level: "B1" },
  { it: "il colloquio", en: "job interview", example: "Ho un colloquio domani.", tag: "lavoro", level: "B1" },
  { it: "assumere", en: "to hire", example: "L'azienda vuole assumere dieci persone.", tag: "lavoro", level: "B1" },
  { it: "licenziare", en: "to fire", example: "Hanno licenziato tre colleghi.", tag: "lavoro", level: "B1" },
  { it: "lo straordinario", en: "overtime", example: "Faccio spesso lo straordinario.", tag: "lavoro", level: "B1" },
  { it: "fare carriera", en: "to advance one's career", example: "Vuole fare carriera in finanza.", tag: "lavoro", level: "B1" },
  { it: "il computer", en: "computer", example: "Il computer non funziona.", tag: "tecnologia", level: "B1" },
  { it: "lo smartphone", en: "smartphone", example: "Ho comprato uno smartphone nuovo.", tag: "tecnologia", level: "B1" },
  { it: "il sito web", en: "website", example: "Visita il nostro sito web.", tag: "tecnologia", level: "B1" },
  { it: "il programma", en: "software/program", example: "Quale programma usi?", tag: "tecnologia", level: "B1" },
  { it: "la password", en: "password", example: "Ho dimenticato la password.", tag: "tecnologia", level: "B1" },
  { it: "aggiornare", en: "to update", example: "Devi aggiornare il sistema.", tag: "tecnologia", level: "B1" },
  { it: "il Wi-Fi", en: "Wi-Fi", example: "Qual è la password del Wi-Fi?", tag: "tecnologia", level: "B1" },
  { it: "caricare", en: "to charge/upload", example: "Devo caricare il telefono.", tag: "tecnologia", level: "B1" },
  { it: "funzionare", en: "to work/function", example: "L'app non funziona bene.", tag: "tecnologia", level: "B1" },
  { it: "il ragazzo", en: "boyfriend", example: "Ti presento il mio ragazzo.", tag: "relazioni", level: "B1" },
  { it: "la ragazza", en: "girlfriend", example: "La mia ragazza è di Napoli.", tag: "relazioni", level: "B1" },
  { it: "fidanzarsi", en: "to get engaged", example: "Si sono fidanzati a Natale.", tag: "relazioni", level: "B1" },
  { it: "sposarsi", en: "to get married", example: "Si sposano a giugno.", tag: "relazioni", level: "B1" },
  { it: "fidarsi", en: "to trust", example: "Mi fido di te.", tag: "relazioni", level: "B1" },
  { it: "volersi bene", en: "to love each other", example: "Ci vogliamo molto bene.", tag: "relazioni", level: "B1" },
  { it: "lasciare", en: "to leave/break up", example: "L'ha lasciata il mese scorso.", tag: "relazioni", level: "B1" },
  { it: "il matrimonio", en: "wedding/marriage", example: "Il matrimonio è a settembre.", tag: "relazioni", level: "B1" },
  { it: "potrei", en: "I could", example: "Potrei aiutarti domani.", tag: "condizionale", level: "B1" },
  { it: "dovrei", en: "I should", example: "Dovrei studiare di più.", tag: "condizionale", level: "B1" },
  { it: "farei", en: "I would do", example: "Al posto tuo, farei diversamente.", tag: "condizionale", level: "B1" },
  { it: "andrei", en: "I would go", example: "Andrei volentieri in Giappone.", tag: "condizionale", level: "B1" },
  { it: "sarebbe", en: "it would be", example: "Sarebbe bello vivere al mare.", tag: "condizionale", level: "B1" },
  { it: "al posto tuo", en: "in your place", example: "Al posto tuo, accetterei.", tag: "condizionale", level: "B1" },
  { it: "volentieri", en: "gladly", example: "Verrei volentieri alla cena.", tag: "condizionale", level: "B1" },
  { it: "se potessi", en: "if I could", example: "Se potessi, vivrei in Italia.", tag: "condizionale", level: "B1" },
  { it: "lo/la", en: "him/her/it", example: "Lo conosco bene.", tag: "pronomi-diretti", level: "B1" },
  { it: "li/le", en: "them (m/f)", example: "Li vedo ogni giorno.", tag: "pronomi-diretti", level: "B1" },
  { it: "mi", en: "me", example: "Mi chiami stasera?", tag: "pronomi-diretti", level: "B1" },
  { it: "ti", en: "you", example: "Ti aspetto alle otto.", tag: "pronomi-diretti", level: "B1" },
  { it: "ci", en: "us", example: "Ci invitano alla festa.", tag: "pronomi-diretti", level: "B1" },
  { it: "conoscere", en: "to know (person)", example: "La conosci quella ragazza?", tag: "pronomi-diretti", level: "B1" },
  { it: "chiamare", en: "to call", example: "Ti chiamo domani.", tag: "pronomi-diretti", level: "B1" },
  { it: "aspettare", en: "to wait for", example: "Ti aspetto fuori.", tag: "pronomi-diretti", level: "B1" },
];

if (A2_AUDIT_EXPANSION.length !== 77) {
  throw new Error(`Expected 77 A2 audit expansion cards, got ${A2_AUDIT_EXPANSION.length}`);
}

if (B1_AUDIT_EXPANSION.length !== 102) {
  throw new Error(`Expected 102 B1 audit expansion cards, got ${B1_AUDIT_EXPANSION.length}`);
}
