export interface FastTrackDocsContentEntry {
  it: string;
  en: string;
  example: string;
  tag: string;
  level: "A1" | "A2" | "B1";
  phase: "phase_1" | "phase_2" | "phase_3";
  patternId: string;
  domain: string;
  sourceRef: "docs/content.txt";
}

// Curated chunk-first content extracted from docs/content.txt and normalized for backend seeding.
// This pack favors reusable sentence patterns over isolated dictionary entries.
export const FAST_TRACK_DOCS_CONTENT: FastTrackDocsContentEntry[] = [
  {
    it: "Mi chiamo Tom.",
    en: "My name is Tom.",
    example: "Mi chiamo Tom.",
    tag: "basics",
    level: "A1",
    phase: "phase_1",
    patternId: "identity_essere",
    domain: "identity",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Sono polacco.",
    en: "I am Polish.",
    example: "Sono polacco.",
    tag: "basics",
    level: "A1",
    phase: "phase_1",
    patternId: "identity_essere",
    domain: "identity",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Sono stanco.",
    en: "I am tired.",
    example: "Sono stanco.",
    tag: "basics",
    level: "A1",
    phase: "phase_1",
    patternId: "identity_essere",
    domain: "identity",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Sono a casa.",
    en: "I am at home.",
    example: "Sono a casa.",
    tag: "home",
    level: "A1",
    phase: "phase_1",
    patternId: "location_essere",
    domain: "location",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Sono in ufficio.",
    en: "I am in the office.",
    example: "Sono in ufficio.",
    tag: "work",
    level: "A1",
    phase: "phase_1",
    patternId: "location_essere",
    domain: "location",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Vivo a Varsavia.",
    en: "I live in Warsaw.",
    example: "Vivo a Varsavia.",
    tag: "basics",
    level: "A1",
    phase: "phase_1",
    patternId: "location_essere",
    domain: "identity",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Lavoro in ufficio.",
    en: "I work in an office.",
    example: "Lavoro in ufficio.",
    tag: "work",
    level: "A1",
    phase: "phase_1",
    patternId: "identity_essere",
    domain: "work",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Studio italiano.",
    en: "I study Italian.",
    example: "Studio italiano.",
    tag: "basics",
    level: "A1",
    phase: "phase_1",
    patternId: "identity_essere",
    domain: "study",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Parlo un po' italiano.",
    en: "I speak a little Italian.",
    example: "Parlo un po' italiano.",
    tag: "basics",
    level: "A1",
    phase: "phase_1",
    patternId: "conversation_repair",
    domain: "conversation",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Ho fame.",
    en: "I am hungry.",
    example: "Ho fame.",
    tag: "food",
    level: "A1",
    phase: "phase_1",
    patternId: "need_ho_bisogno_di",
    domain: "food",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Ho sete.",
    en: "I am thirsty.",
    example: "Ho sete.",
    tag: "food",
    level: "A1",
    phase: "phase_1",
    patternId: "need_ho_bisogno_di",
    domain: "food",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Ho tempo.",
    en: "I have time.",
    example: "Ho tempo.",
    tag: "time",
    level: "A1",
    phase: "phase_1",
    patternId: "need_ho_bisogno_di",
    domain: "time",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Non ho tempo.",
    en: "I do not have time.",
    example: "Non ho tempo.",
    tag: "time",
    level: "A1",
    phase: "phase_1",
    patternId: "need_ho_bisogno_di",
    domain: "time",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Vado al lavoro.",
    en: "I go to work.",
    example: "Vado al lavoro.",
    tag: "work",
    level: "A1",
    phase: "phase_1",
    patternId: "movement_vado",
    domain: "movement",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Vado a casa.",
    en: "I go home.",
    example: "Vado a casa.",
    tag: "home",
    level: "A1",
    phase: "phase_1",
    patternId: "movement_vado",
    domain: "movement",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Vado al ristorante.",
    en: "I go to the restaurant.",
    example: "Vado al ristorante.",
    tag: "food",
    level: "A1",
    phase: "phase_1",
    patternId: "movement_vado",
    domain: "movement",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Mangio alle otto.",
    en: "I eat at eight.",
    example: "Mangio alle otto.",
    tag: "time",
    level: "A1",
    phase: "phase_1",
    patternId: "identity_essere",
    domain: "routine",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Bevo un caffè.",
    en: "I drink a coffee.",
    example: "Bevo un caffè.",
    tag: "food",
    level: "A1",
    phase: "phase_1",
    patternId: "want_voglio",
    domain: "food",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Prendo un taxi.",
    en: "I take a taxi.",
    example: "Prendo un taxi.",
    tag: "travel",
    level: "A1",
    phase: "phase_1",
    patternId: "movement_vado",
    domain: "travel",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Compro pane.",
    en: "I buy bread.",
    example: "Compro pane.",
    tag: "shopping",
    level: "A1",
    phase: "phase_1",
    patternId: "want_voglio",
    domain: "shopping",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Pago il conto.",
    en: "I pay the bill.",
    example: "Pago il conto.",
    tag: "food",
    level: "A1",
    phase: "phase_1",
    patternId: "ability_posso",
    domain: "restaurant",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Come ti chiami?",
    en: "What is your name?",
    example: "Come ti chiami?",
    tag: "basics",
    level: "A1",
    phase: "phase_1",
    patternId: "conversation_repair",
    domain: "conversation",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Di dove sei?",
    en: "Where are you from?",
    example: "Di dove sei?",
    tag: "basics",
    level: "A1",
    phase: "phase_1",
    patternId: "conversation_repair",
    domain: "conversation",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Quanto costa?",
    en: "How much does it cost?",
    example: "Quanto costa?",
    tag: "shopping",
    level: "A1",
    phase: "phase_1",
    patternId: "ability_posso",
    domain: "shopping",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Dov'è il bagno?",
    en: "Where is the bathroom?",
    example: "Dov'è il bagno?",
    tag: "travel",
    level: "A1",
    phase: "phase_1",
    patternId: "location_essere",
    domain: "travel",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Posso entrare?",
    en: "Can I enter?",
    example: "Posso entrare?",
    tag: "basics",
    level: "A1",
    phase: "phase_1",
    patternId: "ability_posso",
    domain: "requests",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Posso pagare con carta?",
    en: "Can I pay by card?",
    example: "Posso pagare con carta?",
    tag: "shopping",
    level: "A1",
    phase: "phase_1",
    patternId: "ability_posso",
    domain: "shopping",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Può aiutarmi?",
    en: "Can you help me?",
    example: "Può aiutarmi?",
    tag: "health",
    level: "A1",
    phase: "phase_1",
    patternId: "conversation_repair",
    domain: "requests",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Vorrei un caffè.",
    en: "I would like a coffee.",
    example: "Vorrei un caffè.",
    tag: "food",
    level: "A1",
    phase: "phase_1",
    patternId: "polite_request_vorrei",
    domain: "restaurant",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Vorrei il conto.",
    en: "I would like the bill.",
    example: "Vorrei il conto.",
    tag: "food",
    level: "A1",
    phase: "phase_1",
    patternId: "polite_request_vorrei",
    domain: "restaurant",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Ho bisogno di aiuto.",
    en: "I need help.",
    example: "Ho bisogno di aiuto.",
    tag: "health",
    level: "A1",
    phase: "phase_1",
    patternId: "need_ho_bisogno_di",
    domain: "requests",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Può ripetere?",
    en: "Can you repeat?",
    example: "Può ripetere?",
    tag: "basics",
    level: "A1",
    phase: "phase_1",
    patternId: "conversation_repair",
    domain: "conversation",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Mi sveglio alle sette.",
    en: "I wake up at seven.",
    example: "Mi sveglio alle sette.",
    tag: "routine",
    level: "A2",
    phase: "phase_2",
    patternId: "identity_essere",
    domain: "routine",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Faccio colazione.",
    en: "I have breakfast.",
    example: "Faccio colazione.",
    tag: "routine",
    level: "A2",
    phase: "phase_2",
    patternId: "identity_essere",
    domain: "routine",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Vado al lavoro in metro.",
    en: "I go to work by metro.",
    example: "Vado al lavoro in metro.",
    tag: "routine",
    level: "A2",
    phase: "phase_2",
    patternId: "movement_vado",
    domain: "routine",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Torno a casa alle sei.",
    en: "I return home at six.",
    example: "Torno a casa alle sei.",
    tag: "routine",
    level: "A2",
    phase: "phase_2",
    patternId: "movement_vado",
    domain: "routine",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Cucino la cena.",
    en: "I cook dinner.",
    example: "Cucino la cena.",
    tag: "routine",
    level: "A2",
    phase: "phase_2",
    patternId: "identity_essere",
    domain: "routine",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Guardo un film.",
    en: "I watch a movie.",
    example: "Guardo un film.",
    tag: "media",
    level: "A2",
    phase: "phase_2",
    patternId: "identity_essere",
    domain: "routine",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Leggo un libro.",
    en: "I read a book.",
    example: "Leggo un libro.",
    tag: "routine",
    level: "A2",
    phase: "phase_2",
    patternId: "identity_essere",
    domain: "routine",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Ascolto musica.",
    en: "I listen to music.",
    example: "Ascolto musica.",
    tag: "routine",
    level: "A2",
    phase: "phase_2",
    patternId: "identity_essere",
    domain: "routine",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Voglio viaggiare.",
    en: "I want to travel.",
    example: "Voglio viaggiare.",
    tag: "travel",
    level: "A2",
    phase: "phase_2",
    patternId: "plan_penso_di",
    domain: "plans",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Devo lavorare.",
    en: "I must work.",
    example: "Devo lavorare.",
    tag: "work",
    level: "A2",
    phase: "phase_2",
    patternId: "obligation_devo",
    domain: "work",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Devo studiare.",
    en: "I must study.",
    example: "Devo studiare.",
    tag: "work",
    level: "A2",
    phase: "phase_2",
    patternId: "obligation_devo",
    domain: "study",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Ho mangiato una pizza.",
    en: "I ate a pizza.",
    example: "Ho mangiato una pizza.",
    tag: "food",
    level: "A2",
    phase: "phase_2",
    patternId: "past_ho_participio",
    domain: "past_events",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Ho bevuto vino.",
    en: "I drank wine.",
    example: "Ho bevuto vino.",
    tag: "food",
    level: "A2",
    phase: "phase_2",
    patternId: "past_ho_participio",
    domain: "past_events",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Ho visto un film.",
    en: "I saw a movie.",
    example: "Ho visto un film.",
    tag: "media",
    level: "A2",
    phase: "phase_2",
    patternId: "past_ho_participio",
    domain: "past_events",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Ho lavorato molto.",
    en: "I worked a lot.",
    example: "Ho lavorato molto.",
    tag: "work",
    level: "A2",
    phase: "phase_2",
    patternId: "past_ho_participio",
    domain: "past_events",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Ho studiato italiano.",
    en: "I studied Italian.",
    example: "Ho studiato italiano.",
    tag: "basics",
    level: "A2",
    phase: "phase_2",
    patternId: "past_ho_participio",
    domain: "past_events",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Ho comprato pane.",
    en: "I bought bread.",
    example: "Ho comprato pane.",
    tag: "shopping",
    level: "A2",
    phase: "phase_2",
    patternId: "past_ho_participio",
    domain: "past_events",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Sono andato al lavoro.",
    en: "I went to work.",
    example: "Sono andato al lavoro.",
    tag: "work",
    level: "A2",
    phase: "phase_2",
    patternId: "past_ho_participio",
    domain: "past_events",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Sono tornato a casa.",
    en: "I returned home.",
    example: "Sono tornato a casa.",
    tag: "home",
    level: "A2",
    phase: "phase_2",
    patternId: "past_ho_participio",
    domain: "past_events",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Mi piace la cucina italiana.",
    en: "I like Italian cuisine.",
    example: "Mi piace la cucina italiana.",
    tag: "food",
    level: "B1",
    phase: "phase_3",
    patternId: "like_mi_piace",
    domain: "preferences",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Mi piace viaggiare.",
    en: "I like travelling.",
    example: "Mi piace viaggiare.",
    tag: "travel",
    level: "B1",
    phase: "phase_3",
    patternId: "like_mi_piace",
    domain: "preferences",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Preferisco il treno.",
    en: "I prefer the train.",
    example: "Preferisco il treno.",
    tag: "travel",
    level: "B1",
    phase: "phase_3",
    patternId: "preference_preferisco",
    domain: "preferences",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Preferisco lavorare da casa.",
    en: "I prefer working from home.",
    example: "Preferisco lavorare da casa.",
    tag: "work",
    level: "B1",
    phase: "phase_3",
    patternId: "preference_preferisco",
    domain: "preferences",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Quando ero piccolo vivevo vicino al mare.",
    en: "When I was a child I lived near the sea.",
    example: "Quando ero piccolo vivevo vicino al mare.",
    tag: "social",
    level: "B1",
    phase: "phase_3",
    patternId: "past_ho_participio",
    domain: "narration",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Da bambino giocavo molto.",
    en: "As a child I played a lot.",
    example: "Da bambino giocavo molto.",
    tag: "social",
    level: "B1",
    phase: "phase_3",
    patternId: "past_ho_participio",
    domain: "narration",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Domani lavorerò.",
    en: "Tomorrow I will work.",
    example: "Domani lavorerò.",
    tag: "work",
    level: "B1",
    phase: "phase_3",
    patternId: "future_simple",
    domain: "plans",
    sourceRef: "docs/content.txt",
  },
  {
    it: "L'anno prossimo viaggerò.",
    en: "Next year I will travel.",
    example: "L'anno prossimo viaggerò.",
    tag: "travel",
    level: "B1",
    phase: "phase_3",
    patternId: "future_simple",
    domain: "plans",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Andrò in Italia.",
    en: "I will go to Italy.",
    example: "Andrò in Italia.",
    tag: "travel",
    level: "B1",
    phase: "phase_3",
    patternId: "future_simple",
    domain: "plans",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Penso di studiare di più.",
    en: "I plan to study more.",
    example: "Penso di studiare di più.",
    tag: "work",
    level: "B1",
    phase: "phase_3",
    patternId: "plan_penso_di",
    domain: "plans",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Secondo me è importante.",
    en: "In my opinion it is important.",
    example: "Secondo me è importante.",
    tag: "opinions",
    level: "B1",
    phase: "phase_3",
    patternId: "opinion_secondo_me",
    domain: "opinions",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Secondo me è troppo caro.",
    en: "In my opinion it is too expensive.",
    example: "Secondo me è troppo caro.",
    tag: "opinions",
    level: "B1",
    phase: "phase_3",
    patternId: "opinion_secondo_me",
    domain: "opinions",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Credo che sia possibile.",
    en: "I believe it is possible.",
    example: "Credo che sia possibile.",
    tag: "opinions",
    level: "B1",
    phase: "phase_3",
    patternId: "opinion_penso_che",
    domain: "opinions",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Studio italiano perché mi piace.",
    en: "I study Italian because I like it.",
    example: "Studio italiano perché mi piace.",
    tag: "basics",
    level: "B1",
    phase: "phase_3",
    patternId: "explanation_perche",
    domain: "reasons",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Voglio viaggiare perché amo l'Italia.",
    en: "I want to travel because I love Italy.",
    example: "Voglio viaggiare perché amo l'Italia.",
    tag: "travel",
    level: "B1",
    phase: "phase_3",
    patternId: "explanation_perche",
    domain: "reasons",
    sourceRef: "docs/content.txt",
  },
  {
    it: "Lavoro molto perché ho molti progetti.",
    en: "I work a lot because I have many projects.",
    example: "Lavoro molto perché ho molti progetti.",
    tag: "work",
    level: "B1",
    phase: "phase_3",
    patternId: "explanation_perche",
    domain: "reasons",
    sourceRef: "docs/content.txt",
  },
];

export const FAST_TRACK_DOCS_SEED_CARDS = FAST_TRACK_DOCS_CONTENT.map(({ it, en, example, tag, level }) => ({
  it,
  en,
  example,
  tag,
  level,
}));
