export type CefrLevel = "A1" | "A2" | "B1" | "B2";

export interface MissionCheckpoint {
  id: string;
  title: string;
  description: string;
  required: boolean;
  minScore: number;
}

export interface MissionTemplate {
  missionId: string;
  title: string;
  level: CefrLevel;
  displayLevel?: CefrLevel;
  order: number;
  required: boolean;
  summary: string;
  scenario: string;
  objective: string;
  tags: string[];
  primarySkills: string[];
  errorFocus: string[];
  criticalErrorTypes: string[];
  exerciseTargets: {
    bronzeReviews: number;
    silverDrills: number;
    goldConversations: number;
    silverAccuracyTarget: number;
    goldPhraseTarget: number;
  };
  exerciseMix: {
    srs: number;
    cloze: number;
    wordBuilder: number;
    patternDrill: number;
    speedTranslation: number;
    errorHunt: number;
    conversation: number;
    reflection: number;
  };
  passPolicy: {
    minCompositeScore: number;
    requireCriticalErrorsZero: boolean;
    checkpoint: string;
  };
  checkpoints?: MissionCheckpoint[];
  prerequisites: string[];
  active: boolean;
}

export interface SkillDefinition {
  skillKey: string;
  label: string;
  domain: string;
  description: string;
  levelBands: CefrLevel[];
  active: boolean;
}

export interface ErrorDefinition {
  errorKey: string;
  label: string;
  description: string;
  category: string;
  severity: "low" | "medium" | "high";
  active: boolean;
}

export interface LevelRoadmap {
  level: CefrLevel;
  nextLevel?: Exclude<CefrLevel, "A1">;
  missionPool: string[];
  requiredMissionIds: string[];
  minCompletedMissions: number;
  minOptionalMissions: number;
  skillThresholds: Array<{ skillKey: string; minPoints: number }>;
  sessionMinimums: {
    bronze: number;
    silver: number;
    gold: number;
    minutes: number;
    activeDays: number;
  };
  finalCheckpointMissionId?: string;
}

export const SKILL_TAXONOMY: SkillDefinition[] = [
  {
    skillKey: "vocab_core",
    label: "Core Vocabulary",
    domain: "vocab",
    description: "Everyday lexical recall and flexible word choice in scenario context.",
    levelBands: ["A1", "A2", "B1", "B2"],
    active: true,
  },
  {
    skillKey: "grammar_forms",
    label: "Grammar Forms",
    domain: "grammar",
    description: "Verb forms, articles, agreements, and morphology control.",
    levelBands: ["A1", "A2", "B1"],
    active: true,
  },
  {
    skillKey: "grammar_syntax",
    label: "Grammar Syntax",
    domain: "grammar",
    description: "Word order, clause links, and sentence architecture.",
    levelBands: ["A1", "A2", "B1", "B2"],
    active: true,
  },
  {
    skillKey: "listening_literal",
    label: "Listening Literal",
    domain: "listening",
    description: "Decode explicit meaning in clear speech.",
    levelBands: ["A1", "A2", "B1"],
    active: true,
  },
  {
    skillKey: "listening_inference",
    label: "Listening Inference",
    domain: "listening",
    description: "Infer implied meaning and constraints from spoken context.",
    levelBands: ["A2", "B1", "B2"],
    active: true,
  },
  {
    skillKey: "speaking_accuracy",
    label: "Speaking Accuracy",
    domain: "speaking",
    description: "Produce grammatically and lexically correct utterances.",
    levelBands: ["A1", "A2", "B1", "B2"],
    active: true,
  },
  {
    skillKey: "speaking_fluency",
    label: "Speaking Fluency",
    domain: "speaking",
    description: "Maintain flow with low hesitation and coherent turns.",
    levelBands: ["A1", "A2", "B1", "B2"],
    active: true,
  },
  {
    skillKey: "pronunciation",
    label: "Pronunciation",
    domain: "speaking",
    description: "Segmental accuracy, stress, rhythm, and intelligibility.",
    levelBands: ["A1", "A2", "B1", "B2"],
    active: true,
  },
  {
    skillKey: "reading_comprehension",
    label: "Reading Comprehension",
    domain: "reading",
    description: "Understand signs, menus, short notices, and practical text.",
    levelBands: ["A1", "A2", "B1"],
    active: true,
  },
  {
    skillKey: "writing_micro",
    label: "Micro Writing",
    domain: "writing",
    description: "Compose short functional written responses.",
    levelBands: ["A1", "A2", "B1"],
    active: true,
  },
  {
    skillKey: "pragmatics",
    label: "Pragmatics & Register",
    domain: "pragmatics",
    description: "Choose appropriate politeness, tone, and interaction strategy.",
    levelBands: ["A1", "A2", "B1", "B2"],
    active: true,
  },
  {
    skillKey: "task_completion",
    label: "Task Completion",
    domain: "task",
    description: "Achieve scenario goals under practical constraints.",
    levelBands: ["A1", "A2", "B1", "B2"],
    active: true,
  },
];

export const ERROR_TAXONOMY: ErrorDefinition[] = [
  {
    errorKey: "lexical_choice",
    label: "Lexical Choice",
    description: "Wrong word selection despite knowing nearby vocabulary.",
    category: "lexical",
    severity: "medium",
    active: true,
  },
  {
    errorKey: "lexical_gap",
    label: "Lexical Gap",
    description: "Missing a required word or phrase for the task.",
    category: "lexical",
    severity: "medium",
    active: true,
  },
  {
    errorKey: "false_friend",
    label: "False Friend",
    description: "Misuse due to deceptive cross-language similarity.",
    category: "lexical",
    severity: "medium",
    active: true,
  },
  {
    errorKey: "verb_tense",
    label: "Verb Tense",
    description: "Incorrect tense selection for context timeline.",
    category: "grammar",
    severity: "high",
    active: true,
  },
  {
    errorKey: "verb_conjugation",
    label: "Verb Conjugation",
    description: "Incorrect person/number form in finite verbs.",
    category: "grammar",
    severity: "medium",
    active: true,
  },
  {
    errorKey: "article_gender_number",
    label: "Article/Gender/Number",
    description: "Mismatch in article, gender, or plural agreement.",
    category: "grammar",
    severity: "medium",
    active: true,
  },
  {
    errorKey: "preposition",
    label: "Preposition",
    description: "Incorrect preposition for location/time/verb frame.",
    category: "grammar",
    severity: "high",
    active: true,
  },
  {
    errorKey: "word_order",
    label: "Word Order",
    description: "Sentence sequence not idiomatic or grammatical.",
    category: "syntax",
    severity: "medium",
    active: true,
  },
  {
    errorKey: "agreement",
    label: "Agreement",
    description: "Subject-verb or noun-adjective agreement error.",
    category: "grammar",
    severity: "medium",
    active: true,
  },
  {
    errorKey: "spelling",
    label: "Spelling",
    description: "Orthographic errors that reduce readability.",
    category: "writing",
    severity: "low",
    active: true,
  },
  {
    errorKey: "pronunciation_segmental",
    label: "Pronunciation Segmental",
    description: "Phoneme-level pronunciation mismatch.",
    category: "pronunciation",
    severity: "medium",
    active: true,
  },
  {
    errorKey: "pronunciation_prosody",
    label: "Pronunciation Prosody",
    description: "Stress, rhythm, or intonation pattern mismatch.",
    category: "pronunciation",
    severity: "medium",
    active: true,
  },
  {
    errorKey: "listening_mishear",
    label: "Listening Mishear",
    description: "Incorrectly decoded heard phrase.",
    category: "listening",
    severity: "high",
    active: true,
  },
  {
    errorKey: "instruction_misread",
    label: "Instruction Misread",
    description: "Task prompt misunderstood or partially ignored.",
    category: "task",
    severity: "medium",
    active: true,
  },
  {
    errorKey: "pragmatic_mismatch",
    label: "Pragmatic Mismatch",
    description: "Register/tone does not match social context.",
    category: "pragmatics",
    severity: "medium",
    active: true,
  },
  {
    errorKey: "incomplete_response",
    label: "Incomplete Response",
    description: "Only part of the required task was addressed.",
    category: "task",
    severity: "high",
    active: true,
  },
  {
    errorKey: "off_topic",
    label: "Off Topic",
    description: "Response diverges from scenario objective.",
    category: "task",
    severity: "high",
    active: true,
  },
  {
    errorKey: "dosage_misunderstood",
    label: "Dosage Misunderstood",
    description: "Medicine dosage/interval interpreted incorrectly.",
    category: "task",
    severity: "high",
    active: true,
  },
  {
    errorKey: "negation_reversal",
    label: "Negation Reversal",
    description: "Meaning inverted due to incorrect negation handling.",
    category: "grammar",
    severity: "high",
    active: true,
  },
];

export const MISSIONS: MissionTemplate[] = [
  {
    missionId: "a1-flat-hunt-48h",
    title: "The 48-Hour Flat Hunt",
    level: "A1",
    displayLevel: "A2",
    order: 1,
    required: true,
    summary: "Secure a room in Rome before your temporary stay expires.",
    scenario: "You have 48 hours to compare apartments, ask essentials, and close a rental safely.",
    objective: "Confirm rent, utilities, location, and move-in date in Italian.",
    tags: ["home", "housing", "neighborhood"],
    primarySkills: ["vocab_core", "grammar_forms", "speaking_accuracy", "task_completion"],
    errorFocus: ["article_gender_number", "preposition", "lexical_gap", "incomplete_response"],
    criticalErrorTypes: ["incomplete_response"],
    exerciseTargets: { bronzeReviews: 50, silverDrills: 24, goldConversations: 3, silverAccuracyTarget: 70, goldPhraseTarget: 10 },
    exerciseMix: { srs: 50, cloze: 8, wordBuilder: 6, patternDrill: 8, speedTranslation: 0, errorHunt: 2, conversation: 3, reflection: 1 },
    passPolicy: { minCompositeScore: 70, requireCriticalErrorsZero: true, checkpoint: "State final rent, bills included, and contract start date." },
    checkpoints: [
      { id: "a1-flat-hunt-48h:listing-scan", title: "Listing Scan", description: "Compare two ads and extract rent, zone, and contract type.", required: true, minScore: 58 },
      { id: "a1-flat-hunt-48h:landlord-call", title: "Landlord Call", description: "Call owner/agent and ask utilities, deposit, and move-in date.", required: true, minScore: 65 },
      { id: "a1-flat-hunt-48h:visit-negotiation", title: "Visit Negotiation", description: "Handle viewing questions and negotiate one condition.", required: false, minScore: 66 },
      { id: "a1-flat-hunt-48h:deal-close", title: "Deal Close", description: "Confirm final offer with all key terms and timeline.", required: true, minScore: 70 },
    ],
    prerequisites: [],
    active: true,
  },
  {
    missionId: "a1-dinner-inlaws",
    title: "Dinner With Future In-Laws",
    level: "A1",
    displayLevel: "A2",
    order: 2,
    required: true,
    summary: "Navigate a full restaurant interaction under social pressure.",
    scenario: "You meet your partner's family and must handle ordering and etiquette cleanly.",
    objective: "Order confidently, clarify needs, and settle the bill politely.",
    tags: ["food", "restaurant", "social"],
    primarySkills: ["vocab_core", "pragmatics", "listening_literal", "speaking_accuracy"],
    errorFocus: ["lexical_choice", "pragmatic_mismatch", "listening_mishear"],
    criticalErrorTypes: ["pragmatic_mismatch"],
    exerciseTargets: { bronzeReviews: 45, silverDrills: 24, goldConversations: 3, silverAccuracyTarget: 72, goldPhraseTarget: 10 },
    exerciseMix: { srs: 45, cloze: 8, wordBuilder: 4, patternDrill: 4, speedTranslation: 6, errorHunt: 2, conversation: 3, reflection: 1 },
    passPolicy: { minCompositeScore: 72, requireCriticalErrorsZero: true, checkpoint: "Ask for the bill and split payment correctly." },
    checkpoints: [
      { id: "a1-dinner-inlaws:arrival-greetings", title: "Arrival Greetings", description: "Introduce yourself and use polite social openers.", required: true, minScore: 58 },
      { id: "a1-dinner-inlaws:order-main", title: "Order Main Course", description: "Order food/drinks, ask clarifications, and show etiquette.", required: true, minScore: 66 },
      { id: "a1-dinner-inlaws:diet-adjustment", title: "Diet Adjustment", description: "Resolve a dietary constraint without confusion.", required: false, minScore: 66 },
      { id: "a1-dinner-inlaws:bill-split", title: "Bill & Split", description: "Ask for the bill and split payment correctly.", required: true, minScore: 72 },
    ],
    prerequisites: [],
    active: true,
  },
  {
    missionId: "a1-last-train",
    title: "Last Train to Florence",
    level: "A1",
    displayLevel: "A2",
    order: 3,
    required: true,
    summary: "Recover from a disrupted route and still arrive tonight.",
    scenario: "A strike affects your route and you must negotiate alternatives at the station.",
    objective: "Obtain ticket, platform, and departure confirmation with fallback options.",
    tags: ["travel", "transport", "time"],
    primarySkills: ["vocab_core", "listening_literal", "task_completion", "speaking_accuracy"],
    errorFocus: ["preposition", "verb_conjugation", "instruction_misread"],
    criticalErrorTypes: ["instruction_misread"],
    exerciseTargets: { bronzeReviews: 45, silverDrills: 24, goldConversations: 4, silverAccuracyTarget: 70, goldPhraseTarget: 12 },
    exerciseMix: { srs: 45, cloze: 8, wordBuilder: 3, patternDrill: 7, speedTranslation: 6, errorHunt: 0, conversation: 4, reflection: 1 },
    passPolicy: { minCompositeScore: 70, requireCriticalErrorsZero: true, checkpoint: "Provide exact itinerary: train, platform, and departure time." },
    checkpoints: [
      { id: "a1-last-train:station-info", title: "Station Information", description: "Ask departure board questions and platform details.", required: true, minScore: 58 },
      { id: "a1-last-train:ticket-recovery", title: "Ticket Recovery", description: "Handle ticket desk dialogue after disruption.", required: true, minScore: 65 },
      { id: "a1-last-train:fallback-route", title: "Fallback Route", description: "Evaluate alternatives and pick viable connection.", required: false, minScore: 66 },
      { id: "a1-last-train:itinerary-confirm", title: "Itinerary Confirm", description: "Repeat exact train, platform, and departure time.", required: true, minScore: 70 },
    ],
    prerequisites: [],
    active: true,
  },
  {
    missionId: "a1-workweek-milan",
    title: "First Week at Work in Milan",
    level: "A1",
    order: 4,
    required: true,
    summary: "Explain your routine and coordinate daily schedules at work.",
    scenario: "Your manager asks for updates on your schedule and tomorrow plan each day.",
    objective: "Describe habits, availability, and simple plans clearly.",
    tags: ["routine", "work", "time"],
    primarySkills: ["grammar_syntax", "speaking_fluency", "writing_micro", "task_completion"],
    errorFocus: ["word_order", "agreement", "verb_tense"],
    criticalErrorTypes: ["incomplete_response"],
    exerciseTargets: { bronzeReviews: 40, silverDrills: 24, goldConversations: 3, silverAccuracyTarget: 72, goldPhraseTarget: 10 },
    exerciseMix: { srs: 40, cloze: 10, wordBuilder: 8, patternDrill: 6, speedTranslation: 0, errorHunt: 0, conversation: 3, reflection: 1 },
    passPolicy: { minCompositeScore: 72, requireCriticalErrorsZero: true, checkpoint: "Deliver a 60-90 second daily routine summary." },
    checkpoints: [
      { id: "a1-workweek-milan:daily-routine", title: "Daily Routine", description: "Describe morning-to-evening routine clearly.", required: true, minScore: 58 },
      { id: "a1-workweek-milan:schedule-sync", title: "Schedule Sync", description: "Report availability and tomorrow plan to manager.", required: true, minScore: 66 },
      { id: "a1-workweek-milan:change-request", title: "Change Request", description: "Handle one schedule change politely.", required: false, minScore: 66 },
      { id: "a1-workweek-milan:routine-wrap", title: "Routine Wrap", description: "Deliver a concise spoken recap of your routine and plans.", required: true, minScore: 72 },
    ],
    prerequisites: [],
    active: true,
  },
  {
    missionId: "a1-shopping-rush",
    title: "Outfit Before the Big Event",
    level: "A1",
    order: 5,
    required: false,
    summary: "Buy a complete outfit under budget and time pressure.",
    scenario: "You have one afternoon, a fixed budget, and a formal dress code.",
    objective: "Ask for size, price, alternatives, and return policy.",
    tags: ["shopping", "money", "social"],
    primarySkills: ["vocab_core", "pragmatics", "task_completion"],
    errorFocus: ["lexical_choice", "article_gender_number", "off_topic"],
    criticalErrorTypes: [],
    exerciseTargets: { bronzeReviews: 40, silverDrills: 20, goldConversations: 3, silverAccuracyTarget: 70, goldPhraseTarget: 8 },
    exerciseMix: { srs: 40, cloze: 8, wordBuilder: 2, patternDrill: 2, speedTranslation: 6, errorHunt: 2, conversation: 3, reflection: 1 },
    passPolicy: { minCompositeScore: 70, requireCriticalErrorsZero: false, checkpoint: "Complete purchase within budget and preferred color/size." },
    checkpoints: [
      { id: "a1-shopping-rush:needs-brief", title: "Needs Brief", description: "State event, style, budget, and timing.", required: true, minScore: 56 },
      { id: "a1-shopping-rush:size-fit", title: "Size & Fit", description: "Ask for sizes and fitting alternatives.", required: true, minScore: 64 },
      { id: "a1-shopping-rush:price-tradeoff", title: "Price Tradeoff", description: "Compare options and choose within budget.", required: false, minScore: 65 },
      { id: "a1-shopping-rush:purchase-close", title: "Purchase Close", description: "Confirm final item, price, and return policy.", required: true, minScore: 70 },
    ],
    prerequisites: [],
    active: true,
  },
  {
    missionId: "a1-midnight-pharmacy",
    title: "Midnight Pharmacy Run",
    level: "A1",
    displayLevel: "A2",
    order: 6,
    required: false,
    summary: "Handle a late-night health issue safely in Italian.",
    scenario: "You need medicine at night before a critical next-day commitment.",
    objective: "Describe symptoms, understand dosage, and confirm warnings.",
    tags: ["health", "pharmacy", "safety"],
    primarySkills: ["vocab_core", "listening_literal", "speaking_accuracy", "task_completion"],
    errorFocus: ["lexical_gap", "preposition", "incomplete_response"],
    criticalErrorTypes: ["dosage_misunderstood", "negation_reversal"],
    exerciseTargets: { bronzeReviews: 35, silverDrills: 20, goldConversations: 3, silverAccuracyTarget: 72, goldPhraseTarget: 8 },
    exerciseMix: { srs: 35, cloze: 8, wordBuilder: 0, patternDrill: 6, speedTranslation: 0, errorHunt: 6, conversation: 3, reflection: 1 },
    passPolicy: { minCompositeScore: 72, requireCriticalErrorsZero: true, checkpoint: "Repeat dosage schedule and contraindications correctly." },
    checkpoints: [
      { id: "a1-midnight-pharmacy:symptom-report", title: "Symptom Report", description: "Describe symptoms and duration clearly.", required: true, minScore: 58 },
      { id: "a1-midnight-pharmacy:dosage-clarify", title: "Dosage Clarify", description: "Ask and repeat dosage and frequency.", required: true, minScore: 68 },
      { id: "a1-midnight-pharmacy:warning-check", title: "Warning Check", description: "Confirm contraindications and timing.", required: false, minScore: 68 },
      { id: "a1-midnight-pharmacy:safe-summary", title: "Safe Summary", description: "Summarize full medicine plan safely.", required: true, minScore: 72 },
    ],
    prerequisites: [],
    active: true,
  },
  {
    missionId: "a1-social-circle",
    title: "Build Your Social Circle",
    level: "A1",
    displayLevel: "A2",
    order: 7,
    required: false,
    summary: "Plan and coordinate your first weekend meetup in Italian.",
    scenario: "You invite three new friends and must negotiate logistics and changes.",
    objective: "Get final yes/no responses with clear time and location.",
    tags: ["social", "routine", "planning"],
    primarySkills: ["speaking_fluency", "pragmatics", "task_completion"],
    errorFocus: ["pragmatic_mismatch", "word_order", "off_topic"],
    criticalErrorTypes: [],
    exerciseTargets: { bronzeReviews: 35, silverDrills: 20, goldConversations: 3, silverAccuracyTarget: 70, goldPhraseTarget: 8 },
    exerciseMix: { srs: 35, cloze: 6, wordBuilder: 8, patternDrill: 0, speedTranslation: 6, errorHunt: 0, conversation: 3, reflection: 1 },
    passPolicy: { minCompositeScore: 70, requireCriticalErrorsZero: false, checkpoint: "Confirm final meetup with all participants." },
    checkpoints: [
      { id: "a1-social-circle:invite-open", title: "Invite Open", description: "Invite friends and propose place/time.", required: true, minScore: 56 },
      { id: "a1-social-circle:time-negotiate", title: "Time Negotiate", description: "Handle conflicting schedules.", required: true, minScore: 64 },
      { id: "a1-social-circle:plan-adjust", title: "Plan Adjust", description: "Recover from one cancellation.", required: false, minScore: 64 },
      { id: "a1-social-circle:final-confirm", title: "Final Confirm", description: "Confirm final meetup details with all participants.", required: true, minScore: 70 },
    ],
    prerequisites: [],
    active: true,
  },
  {
    missionId: "a1-final-day-test",
    title: "A Day That Tests Everything",
    level: "A1",
    displayLevel: "A2",
    order: 8,
    required: true,
    summary: "Survive a full day in Italian across core life scenarios.",
    scenario: "You must solve housing, transport, food, and social tasks in one chain.",
    objective: "Complete five linked interactions without switching language.",
    tags: ["home", "travel", "food", "social"],
    primarySkills: ["task_completion", "speaking_accuracy", "listening_literal", "pragmatics"],
    errorFocus: ["incomplete_response", "off_topic", "preposition"],
    criticalErrorTypes: ["incomplete_response", "off_topic"],
    exerciseTargets: { bronzeReviews: 60, silverDrills: 30, goldConversations: 5, silverAccuracyTarget: 75, goldPhraseTarget: 14 },
    exerciseMix: { srs: 60, cloze: 8, wordBuilder: 6, patternDrill: 6, speedTranslation: 4, errorHunt: 6, conversation: 5, reflection: 2 },
    passPolicy: { minCompositeScore: 75, requireCriticalErrorsZero: true, checkpoint: "Finish full mission chain with all mandatory facts confirmed." },
    checkpoints: [
      { id: "a1-final-day-test:morning-chain", title: "Morning Chain", description: "Complete first linked interactions without switching language.", required: true, minScore: 60 },
      { id: "a1-final-day-test:midday-chain", title: "Midday Chain", description: "Handle transport + food constraints accurately.", required: true, minScore: 68 },
      { id: "a1-final-day-test:evening-chain", title: "Evening Chain", description: "Resolve one surprise issue in real time.", required: false, minScore: 70 },
      { id: "a1-final-day-test:full-day-close", title: "Full-Day Close", description: "Finish all mandatory facts across the chain.", required: true, minScore: 75 },
    ],
    prerequisites: ["a1-flat-hunt-48h", "a1-dinner-inlaws", "a1-last-train", "a1-workweek-milan"],
    active: true,
  },

  {
    missionId: "a2-roommate-reset",
    title: "Roommate Conflict Reset",
    level: "A2",
    order: 1,
    required: true,
    summary: "Resolve shared apartment conflict and agree on rules.",
    scenario: "Noise, chores, and bill splits create tension with your roommate.",
    objective: "Negotiate clear rules and compromises in Italian.",
    tags: ["home", "social", "negotiation"],
    primarySkills: ["pragmatics", "speaking_accuracy", "grammar_syntax", "task_completion"],
    errorFocus: ["pragmatic_mismatch", "agreement", "incomplete_response"],
    criticalErrorTypes: ["off_topic"],
    exerciseTargets: { bronzeReviews: 55, silverDrills: 28, goldConversations: 4, silverAccuracyTarget: 74, goldPhraseTarget: 12 },
    exerciseMix: { srs: 55, cloze: 8, wordBuilder: 5, patternDrill: 7, speedTranslation: 2, errorHunt: 6, conversation: 4, reflection: 1 },
    passPolicy: { minCompositeScore: 74, requireCriticalErrorsZero: true, checkpoint: "Finalize 4 house rules and one compromise." },
    checkpoints: [
      { id: "a2-roommate-reset:issue-mapping", title: "Issue Mapping", description: "State conflict causes and desired outcomes.", required: true, minScore: 62 },
      { id: "a2-roommate-reset:rules-negotiation", title: "Rules Negotiation", description: "Negotiate chores, noise, and shared costs.", required: true, minScore: 70 },
      { id: "a2-roommate-reset:compromise-test", title: "Compromise Test", description: "Resolve one hard objection collaboratively.", required: false, minScore: 70 },
      { id: "a2-roommate-reset:agreement-freeze", title: "Agreement Freeze", description: "Finalize explicit house rules and follow-up.", required: true, minScore: 74 },
    ],
    prerequisites: ["a1-final-day-test"],
    active: true,
  },
  {
    missionId: "a2-customer-support-call",
    title: "Customer Support Escalation",
    level: "A2",
    order: 2,
    required: true,
    summary: "Fix a billing mistake through multi-step support calls.",
    scenario: "A service charged you incorrectly and support keeps redirecting you.",
    objective: "Explain issue, request evidence, and secure correction.",
    tags: ["work", "money", "bureaucracy"],
    primarySkills: ["task_completion", "speaking_fluency", "listening_inference", "writing_micro"],
    errorFocus: ["instruction_misread", "word_order", "incomplete_response"],
    criticalErrorTypes: ["incomplete_response"],
    exerciseTargets: { bronzeReviews: 50, silverDrills: 28, goldConversations: 4, silverAccuracyTarget: 75, goldPhraseTarget: 12 },
    exerciseMix: { srs: 50, cloze: 7, wordBuilder: 6, patternDrill: 5, speedTranslation: 4, errorHunt: 6, conversation: 4, reflection: 1 },
    passPolicy: { minCompositeScore: 75, requireCriticalErrorsZero: true, checkpoint: "Obtain ticket ID, refund timeline, and written confirmation." },
    checkpoints: [
      { id: "a2-customer-support-call:problem-brief", title: "Problem Brief", description: "Explain billing issue with evidence.", required: true, minScore: 62 },
      { id: "a2-customer-support-call:escalation-loop", title: "Escalation Loop", description: "Navigate transfers and keep case context.", required: true, minScore: 70 },
      { id: "a2-customer-support-call:proof-request", title: "Proof Request", description: "Request written confirmation and timeline.", required: false, minScore: 70 },
      { id: "a2-customer-support-call:resolution-lock", title: "Resolution Lock", description: "Close call with ticket ID and next steps.", required: true, minScore: 75 },
    ],
    prerequisites: ["a1-final-day-test"],
    active: true,
  },
  {
    missionId: "a2-family-visit-plan",
    title: "Family Visit Logistics",
    level: "A2",
    order: 3,
    required: true,
    summary: "Coordinate travel, lodging, and schedule for family visitors.",
    scenario: "Your family visits Italy and expects you to plan and communicate everything.",
    objective: "Manage schedules, preferences, and last-minute changes.",
    tags: ["travel", "social", "planning"],
    primarySkills: ["speaking_fluency", "listening_inference", "task_completion"],
    errorFocus: ["verb_tense", "preposition", "off_topic"],
    criticalErrorTypes: ["off_topic"],
    exerciseTargets: { bronzeReviews: 50, silverDrills: 26, goldConversations: 4, silverAccuracyTarget: 74, goldPhraseTarget: 12 },
    exerciseMix: { srs: 50, cloze: 8, wordBuilder: 4, patternDrill: 6, speedTranslation: 4, errorHunt: 4, conversation: 4, reflection: 1 },
    passPolicy: { minCompositeScore: 74, requireCriticalErrorsZero: true, checkpoint: "Deliver complete 3-day itinerary and fallback plans." },
    checkpoints: [
      { id: "a2-family-visit-plan:requirements-gather", title: "Requirements Gather", description: "Collect family preferences and constraints.", required: true, minScore: 62 },
      { id: "a2-family-visit-plan:itinerary-draft", title: "Itinerary Draft", description: "Present day-by-day plan with timings.", required: true, minScore: 70 },
      { id: "a2-family-visit-plan:change-management", title: "Change Management", description: "Handle a last-minute plan change.", required: false, minScore: 70 },
      { id: "a2-family-visit-plan:final-brief", title: "Final Brief", description: "Deliver complete 3-day plan with fallback.", required: true, minScore: 74 },
    ],
    prerequisites: ["a1-final-day-test"],
    active: true,
  },
  {
    missionId: "a2-neighborhood-committee",
    title: "Neighborhood Committee Meeting",
    level: "A2",
    order: 4,
    required: false,
    summary: "Participate in local meeting and defend your proposal.",
    scenario: "Residents discuss noise, parking, and renovation priorities.",
    objective: "Present your position and respond to objections.",
    tags: ["home", "bureaucracy", "social"],
    primarySkills: ["pragmatics", "speaking_accuracy", "reading_comprehension"],
    errorFocus: ["pragmatic_mismatch", "lexical_choice", "agreement"],
    criticalErrorTypes: [],
    exerciseTargets: { bronzeReviews: 45, silverDrills: 24, goldConversations: 3, silverAccuracyTarget: 74, goldPhraseTarget: 10 },
    exerciseMix: { srs: 45, cloze: 6, wordBuilder: 4, patternDrill: 6, speedTranslation: 2, errorHunt: 6, conversation: 3, reflection: 1 },
    passPolicy: { minCompositeScore: 74, requireCriticalErrorsZero: false, checkpoint: "State proposal, one compromise, and final vote preference." },
    checkpoints: [
      { id: "a2-neighborhood-committee:proposal-open", title: "Proposal Open", description: "Introduce your proposal in the meeting.", required: true, minScore: 62 },
      { id: "a2-neighborhood-committee:objection-response", title: "Objection Response", description: "Address two resident objections clearly.", required: true, minScore: 70 },
      { id: "a2-neighborhood-committee:compromise-frame", title: "Compromise Frame", description: "Offer realistic compromise option.", required: false, minScore: 70 },
      { id: "a2-neighborhood-committee:vote-close", title: "Vote Close", description: "State final position and expected outcome.", required: true, minScore: 74 },
    ],
    prerequisites: ["a1-final-day-test"],
    active: true,
  },
  {
    missionId: "a2-travel-disruption-chain",
    title: "Multi-Leg Travel Disruption",
    level: "A2",
    order: 5,
    required: false,
    summary: "Handle cascading disruptions across train and bus legs.",
    scenario: "Delays create missed connections and booking conflicts.",
    objective: "Recover route while keeping budget and timing constraints.",
    tags: ["travel", "money", "time"],
    primarySkills: ["task_completion", "listening_inference", "speaking_accuracy"],
    errorFocus: ["instruction_misread", "preposition", "incomplete_response"],
    criticalErrorTypes: ["instruction_misread"],
    exerciseTargets: { bronzeReviews: 48, silverDrills: 26, goldConversations: 4, silverAccuracyTarget: 75, goldPhraseTarget: 12 },
    exerciseMix: { srs: 48, cloze: 6, wordBuilder: 2, patternDrill: 8, speedTranslation: 6, errorHunt: 4, conversation: 4, reflection: 1 },
    passPolicy: { minCompositeScore: 75, requireCriticalErrorsZero: true, checkpoint: "Confirm final route with exact times and ticket classes." },
    checkpoints: [
      { id: "a2-travel-disruption-chain:disruption-diagnosis", title: "Disruption Diagnosis", description: "Identify failed connection and constraints.", required: true, minScore: 62 },
      { id: "a2-travel-disruption-chain:rebooking-flow", title: "Rebooking Flow", description: "Rebook legs while preserving budget.", required: true, minScore: 70 },
      { id: "a2-travel-disruption-chain:constraint-tradeoff", title: "Constraint Tradeoff", description: "Choose between time and cost options.", required: false, minScore: 70 },
      { id: "a2-travel-disruption-chain:route-confirm", title: "Route Confirm", description: "Confirm final route with exact times.", required: true, minScore: 75 },
    ],
    prerequisites: ["a1-final-day-test"],
    active: true,
  },
  {
    missionId: "a2-health-followup",
    title: "Health Follow-Up Loop",
    level: "A2",
    order: 6,
    required: false,
    summary: "From symptoms to check-up to recovery instructions.",
    scenario: "You need a full health interaction sequence with paperwork and advice.",
    objective: "Explain history, understand instructions, and summarize plan.",
    tags: ["health", "bureaucracy", "safety"],
    primarySkills: ["listening_literal", "speaking_accuracy", "task_completion"],
    errorFocus: ["lexical_gap", "negation_reversal", "incomplete_response"],
    criticalErrorTypes: ["dosage_misunderstood", "negation_reversal"],
    exerciseTargets: { bronzeReviews: 46, silverDrills: 24, goldConversations: 4, silverAccuracyTarget: 75, goldPhraseTarget: 10 },
    exerciseMix: { srs: 46, cloze: 8, wordBuilder: 0, patternDrill: 6, speedTranslation: 2, errorHunt: 8, conversation: 4, reflection: 1 },
    passPolicy: { minCompositeScore: 75, requireCriticalErrorsZero: true, checkpoint: "Summarize treatment plan with schedule and restrictions." },
    checkpoints: [
      { id: "a2-health-followup:history-brief", title: "History Brief", description: "Explain symptoms and prior treatment.", required: true, minScore: 62 },
      { id: "a2-health-followup:instruction-decode", title: "Instruction Decode", description: "Understand and restate care instructions.", required: true, minScore: 70 },
      { id: "a2-health-followup:risk-check", title: "Risk Check", description: "Clarify restrictions and warning signs.", required: false, minScore: 70 },
      { id: "a2-health-followup:treatment-summary", title: "Treatment Summary", description: "Summarize schedule and restrictions precisely.", required: true, minScore: 75 },
    ],
    prerequisites: ["a1-midnight-pharmacy"],
    active: true,
  },
  {
    missionId: "a2-final-city-week",
    title: "A2 City Survival Week",
    level: "A2",
    order: 7,
    required: true,
    summary: "Complete a full week of practical urban interactions.",
    scenario: "You operate independently in Italian across admin, travel, housing, and social tasks.",
    objective: "Close all city survival objectives while staying accurate and polite.",
    tags: ["home", "travel", "bureaucracy", "social"],
    primarySkills: ["task_completion", "pragmatics", "speaking_fluency", "listening_inference"],
    errorFocus: ["off_topic", "incomplete_response", "pragmatic_mismatch"],
    criticalErrorTypes: ["off_topic", "incomplete_response"],
    exerciseTargets: { bronzeReviews: 65, silverDrills: 34, goldConversations: 6, silverAccuracyTarget: 78, goldPhraseTarget: 16 },
    exerciseMix: { srs: 65, cloze: 8, wordBuilder: 6, patternDrill: 6, speedTranslation: 4, errorHunt: 10, conversation: 6, reflection: 2 },
    passPolicy: { minCompositeScore: 78, requireCriticalErrorsZero: true, checkpoint: "Complete 5 linked tasks with all constraints satisfied." },
    checkpoints: [
      { id: "a2-final-city-week:task-chain-1", title: "Task Chain I", description: "Complete first set of linked city tasks.", required: true, minScore: 65 },
      { id: "a2-final-city-week:task-chain-2", title: "Task Chain II", description: "Handle admin + travel + social handoffs.", required: true, minScore: 72 },
      { id: "a2-final-city-week:crisis-recovery", title: "Crisis Recovery", description: "Recover from scenario shock without derailment.", required: false, minScore: 74 },
      { id: "a2-final-city-week:mission-completion", title: "Mission Completion", description: "Close all city survival objectives with constraints met.", required: true, minScore: 78 },
    ],
    prerequisites: ["a2-roommate-reset", "a2-customer-support-call", "a2-family-visit-plan"],
    active: true,
  },

  {
    missionId: "b1-startup-pitch",
    title: "Startup Partner Pitch",
    level: "B1",
    order: 1,
    required: true,
    summary: "Pitch your product and handle partner objections.",
    scenario: "You must present roadmap, tradeoffs, and next steps in a partner meeting.",
    objective: "Deliver pitch and survive Q&A with clear argumentation.",
    tags: ["work", "tech", "negotiation"],
    primarySkills: ["speaking_fluency", "speaking_accuracy", "pragmatics", "task_completion"],
    errorFocus: ["word_order", "verb_tense", "off_topic"],
    criticalErrorTypes: ["off_topic"],
    exerciseTargets: { bronzeReviews: 60, silverDrills: 32, goldConversations: 5, silverAccuracyTarget: 78, goldPhraseTarget: 14 },
    exerciseMix: { srs: 60, cloze: 8, wordBuilder: 4, patternDrill: 8, speedTranslation: 2, errorHunt: 10, conversation: 5, reflection: 2 },
    passPolicy: { minCompositeScore: 78, requireCriticalErrorsZero: true, checkpoint: "Answer 4 investor objections with coherent rationale." },
    checkpoints: [
      { id: "b1-startup-pitch:pitch-structure", title: "Pitch Structure", description: "Deliver clear problem-solution-value narrative.", required: true, minScore: 66 },
      { id: "b1-startup-pitch:objection-handling", title: "Objection Handling", description: "Handle cost and feasibility objections.", required: true, minScore: 74 },
      { id: "b1-startup-pitch:tradeoff-reasoning", title: "Tradeoff Reasoning", description: "Explain one strategic tradeoff with rationale.", required: false, minScore: 76 },
      { id: "b1-startup-pitch:qna-close", title: "Q&A Close", description: "Finish investor Q&A with coherent next steps.", required: true, minScore: 78 },
    ],
    prerequisites: ["a2-final-city-week"],
    active: true,
  },
  {
    missionId: "b1-housing-negotiation",
    title: "Complex Housing Negotiation",
    level: "B1",
    order: 2,
    required: true,
    summary: "Negotiate long-term lease with clauses and conditions.",
    scenario: "You need favorable terms and must discuss legal and practical tradeoffs.",
    objective: "Reach agreement while protecting your constraints.",
    tags: ["home", "money", "bureaucracy"],
    primarySkills: ["grammar_syntax", "pragmatics", "task_completion", "writing_micro"],
    errorFocus: ["preposition", "agreement", "incomplete_response"],
    criticalErrorTypes: ["incomplete_response"],
    exerciseTargets: { bronzeReviews: 58, silverDrills: 30, goldConversations: 5, silverAccuracyTarget: 78, goldPhraseTarget: 14 },
    exerciseMix: { srs: 58, cloze: 8, wordBuilder: 6, patternDrill: 6, speedTranslation: 2, errorHunt: 8, conversation: 5, reflection: 1 },
    passPolicy: { minCompositeScore: 78, requireCriticalErrorsZero: true, checkpoint: "Finalize rent, duration, penalties, and maintenance terms." },
    checkpoints: [
      { id: "b1-housing-negotiation:terms-setup", title: "Terms Setup", description: "State priorities and non-negotiables.", required: true, minScore: 66 },
      { id: "b1-housing-negotiation:clause-negotiation", title: "Clause Negotiation", description: "Negotiate contract clauses and penalties.", required: true, minScore: 74 },
      { id: "b1-housing-negotiation:counteroffer-round", title: "Counteroffer Round", description: "Respond to counteroffer under pressure.", required: false, minScore: 76 },
      { id: "b1-housing-negotiation:agreement-signoff", title: "Agreement Signoff", description: "Confirm full lease terms and responsibilities.", required: true, minScore: 78 },
    ],
    prerequisites: ["a2-final-city-week"],
    active: true,
  },
  {
    missionId: "b1-media-interview",
    title: "Local Media Interview",
    level: "B1",
    order: 3,
    required: true,
    summary: "Handle a radio interview on your project and decisions.",
    scenario: "A journalist asks direct and follow-up questions with time pressure.",
    objective: "Answer clearly, stay on message, and sound natural.",
    tags: ["media", "work", "social"],
    primarySkills: ["speaking_fluency", "listening_inference", "pragmatics"],
    errorFocus: ["off_topic", "pragmatic_mismatch", "pronunciation_prosody"],
    criticalErrorTypes: ["off_topic"],
    exerciseTargets: { bronzeReviews: 54, silverDrills: 28, goldConversations: 5, silverAccuracyTarget: 79, goldPhraseTarget: 14 },
    exerciseMix: { srs: 54, cloze: 6, wordBuilder: 2, patternDrill: 6, speedTranslation: 4, errorHunt: 10, conversation: 5, reflection: 2 },
    passPolicy: { minCompositeScore: 79, requireCriticalErrorsZero: true, checkpoint: "Complete interview with coherent opening, evidence, and closing." },
    checkpoints: [
      { id: "b1-media-interview:message-open", title: "Message Open", description: "Open interview with clear thesis.", required: true, minScore: 66 },
      { id: "b1-media-interview:followup-defense", title: "Follow-up Defense", description: "Handle probing follow-up questions.", required: true, minScore: 74 },
      { id: "b1-media-interview:tone-control", title: "Tone Control", description: "Maintain register and composure under pressure.", required: false, minScore: 76 },
      { id: "b1-media-interview:interview-finish", title: "Interview Finish", description: "Close interview with coherent takeaway.", required: true, minScore: 79 },
    ],
    prerequisites: ["a2-final-city-week"],
    active: true,
  },
  {
    missionId: "b1-team-conflict-mediation",
    title: "Team Conflict Mediation",
    level: "B1",
    order: 4,
    required: false,
    summary: "Mediate workplace conflict and secure an action plan.",
    scenario: "Two team members disagree on priorities and communication style.",
    objective: "Align stakeholders and define accountable next steps.",
    tags: ["work", "social", "negotiation"],
    primarySkills: ["pragmatics", "speaking_accuracy", "task_completion"],
    errorFocus: ["pragmatic_mismatch", "incomplete_response", "word_order"],
    criticalErrorTypes: [],
    exerciseTargets: { bronzeReviews: 50, silverDrills: 28, goldConversations: 4, silverAccuracyTarget: 78, goldPhraseTarget: 12 },
    exerciseMix: { srs: 50, cloze: 6, wordBuilder: 4, patternDrill: 8, speedTranslation: 2, errorHunt: 8, conversation: 4, reflection: 2 },
    passPolicy: { minCompositeScore: 78, requireCriticalErrorsZero: false, checkpoint: "Define shared plan with owners and deadlines." },
    checkpoints: [
      { id: "b1-team-conflict-mediation:conflict-diagnosis", title: "Conflict Diagnosis", description: "Summarize positions and friction points.", required: true, minScore: 66 },
      { id: "b1-team-conflict-mediation:mediation-round", title: "Mediation Round", description: "Facilitate dialogue to shared priorities.", required: true, minScore: 74 },
      { id: "b1-team-conflict-mediation:accountability-check", title: "Accountability Check", description: "Assign owners and deadlines.", required: false, minScore: 76 },
      { id: "b1-team-conflict-mediation:plan-lock", title: "Plan Lock", description: "Finalize action plan accepted by all sides.", required: true, minScore: 78 },
    ],
    prerequisites: ["a2-final-city-week"],
    active: true,
  },
  {
    missionId: "b1-bureaucracy-marathon",
    title: "Bureaucracy Marathon",
    level: "B1",
    order: 5,
    required: false,
    summary: "Process multiple administrative tasks in one day.",
    scenario: "You need permits, forms, and appointments across several offices.",
    objective: "Collect all required documents with no missed requirement.",
    tags: ["bureaucracy", "travel", "work"],
    primarySkills: ["reading_comprehension", "writing_micro", "task_completion", "listening_inference"],
    errorFocus: ["instruction_misread", "lexical_gap", "incomplete_response"],
    criticalErrorTypes: ["instruction_misread"],
    exerciseTargets: { bronzeReviews: 52, silverDrills: 30, goldConversations: 4, silverAccuracyTarget: 79, goldPhraseTarget: 12 },
    exerciseMix: { srs: 52, cloze: 6, wordBuilder: 4, patternDrill: 6, speedTranslation: 4, errorHunt: 10, conversation: 4, reflection: 2 },
    passPolicy: { minCompositeScore: 79, requireCriticalErrorsZero: true, checkpoint: "Submit all forms with zero missing mandatory field." },
    checkpoints: [
      { id: "b1-bureaucracy-marathon:document-audit", title: "Document Audit", description: "Identify required forms and missing documents.", required: true, minScore: 66 },
      { id: "b1-bureaucracy-marathon:office-rotation", title: "Office Rotation", description: "Handle multi-counter interactions efficiently.", required: true, minScore: 74 },
      { id: "b1-bureaucracy-marathon:exception-case", title: "Exception Case", description: "Resolve one non-standard requirement.", required: false, minScore: 76 },
      { id: "b1-bureaucracy-marathon:submission-complete", title: "Submission Complete", description: "Submit all forms with zero missing fields.", required: true, minScore: 79 },
    ],
    prerequisites: ["a2-final-city-week"],
    active: true,
  },
  {
    missionId: "b1-community-event",
    title: "Community Event Organizer",
    level: "B1",
    order: 6,
    required: false,
    summary: "Organize and promote a local event with partners.",
    scenario: "You coordinate venue, volunteers, promotion, and contingency plan.",
    objective: "Deliver event brief and stakeholder alignment.",
    tags: ["social", "work", "planning"],
    primarySkills: ["speaking_fluency", "writing_micro", "task_completion", "pragmatics"],
    errorFocus: ["off_topic", "agreement", "pragmatic_mismatch"],
    criticalErrorTypes: [],
    exerciseTargets: { bronzeReviews: 48, silverDrills: 26, goldConversations: 4, silverAccuracyTarget: 78, goldPhraseTarget: 12 },
    exerciseMix: { srs: 48, cloze: 6, wordBuilder: 6, patternDrill: 4, speedTranslation: 2, errorHunt: 8, conversation: 4, reflection: 2 },
    passPolicy: { minCompositeScore: 78, requireCriticalErrorsZero: false, checkpoint: "Publish final event plan with roles and timing." },
    checkpoints: [
      { id: "b1-community-event:event-brief", title: "Event Brief", description: "Present event objective, audience, and format.", required: true, minScore: 66 },
      { id: "b1-community-event:stakeholder-alignment", title: "Stakeholder Alignment", description: "Align partners, volunteers, and venue.", required: true, minScore: 74 },
      { id: "b1-community-event:contingency-run", title: "Contingency Run", description: "Adapt plan for one disruption.", required: false, minScore: 76 },
      { id: "b1-community-event:launch-ready", title: "Launch Ready", description: "Publish final plan with roles and timing.", required: true, minScore: 78 },
    ],
    prerequisites: ["a2-final-city-week"],
    active: true,
  },
  {
    missionId: "b1-final-b2-bridge",
    title: "B2 Bridge: High-Stakes Week",
    level: "B1",
    order: 7,
    required: true,
    summary: "Integrated performance week designed to unlock B2 track.",
    scenario: "You must persuade, negotiate, and explain under changing constraints.",
    objective: "Sustain advanced interaction quality across mixed scenarios.",
    tags: ["work", "bureaucracy", "social", "media"],
    primarySkills: ["listening_inference", "speaking_fluency", "pragmatics", "task_completion"],
    errorFocus: ["off_topic", "incomplete_response", "pragmatic_mismatch", "verb_tense"],
    criticalErrorTypes: ["off_topic", "incomplete_response"],
    exerciseTargets: { bronzeReviews: 70, silverDrills: 38, goldConversations: 7, silverAccuracyTarget: 82, goldPhraseTarget: 18 },
    exerciseMix: { srs: 70, cloze: 8, wordBuilder: 6, patternDrill: 8, speedTranslation: 4, errorHunt: 12, conversation: 7, reflection: 3 },
    passPolicy: { minCompositeScore: 82, requireCriticalErrorsZero: true, checkpoint: "Complete 6 linked tasks with explicit tradeoff reasoning." },
    checkpoints: [
      { id: "b1-final-b2-bridge:high-stakes-open", title: "High-Stakes Open", description: "Start integrated week with clear strategy.", required: true, minScore: 70 },
      { id: "b1-final-b2-bridge:multi-domain-exec", title: "Multi-Domain Execution", description: "Sustain quality across mixed domains.", required: true, minScore: 78 },
      { id: "b1-final-b2-bridge:tradeoff-defense", title: "Tradeoff Defense", description: "Defend decisions with explicit tradeoff logic.", required: false, minScore: 80 },
      { id: "b1-final-b2-bridge:bridge-completion", title: "Bridge Completion", description: "Complete all linked tasks at B2-entry quality.", required: true, minScore: 82 },
    ],
    prerequisites: ["b1-startup-pitch", "b1-housing-negotiation", "b1-media-interview"],
    active: true,
  },
];

export const LEVEL_ROADMAPS: LevelRoadmap[] = [
  {
    level: "A1",
    nextLevel: "A2",
    missionPool: [
      "a1-flat-hunt-48h",
      "a1-dinner-inlaws",
      "a1-last-train",
      "a1-workweek-milan",
      "a1-shopping-rush",
      "a1-midnight-pharmacy",
      "a1-social-circle",
      "a1-final-day-test",
    ],
    requiredMissionIds: [
      "a1-flat-hunt-48h",
      "a1-dinner-inlaws",
      "a1-last-train",
      "a1-workweek-milan",
      "a1-final-day-test",
    ],
    minCompletedMissions: 6,
    minOptionalMissions: 1,
    skillThresholds: [
      { skillKey: "vocab_core", minPoints: 220 },
      { skillKey: "grammar_forms", minPoints: 180 },
      { skillKey: "listening_literal", minPoints: 140 },
      { skillKey: "speaking_accuracy", minPoints: 140 },
      { skillKey: "task_completion", minPoints: 160 },
    ],
    sessionMinimums: { bronze: 30, silver: 20, gold: 8, minutes: 900, activeDays: 24 },
    finalCheckpointMissionId: "a1-final-day-test",
  },
  {
    level: "A2",
    nextLevel: "B1",
    missionPool: [
      "a2-roommate-reset",
      "a2-customer-support-call",
      "a2-family-visit-plan",
      "a2-neighborhood-committee",
      "a2-travel-disruption-chain",
      "a2-health-followup",
      "a2-final-city-week",
    ],
    requiredMissionIds: [
      "a2-roommate-reset",
      "a2-customer-support-call",
      "a2-family-visit-plan",
      "a2-final-city-week",
    ],
    minCompletedMissions: 5,
    minOptionalMissions: 1,
    skillThresholds: [
      { skillKey: "vocab_core", minPoints: 420 },
      { skillKey: "grammar_syntax", minPoints: 300 },
      { skillKey: "listening_inference", minPoints: 210 },
      { skillKey: "speaking_fluency", minPoints: 220 },
      { skillKey: "pragmatics", minPoints: 180 },
      { skillKey: "task_completion", minPoints: 260 },
    ],
    sessionMinimums: { bronze: 45, silver: 30, gold: 14, minutes: 1400, activeDays: 32 },
    finalCheckpointMissionId: "a2-final-city-week",
  },
  {
    level: "B1",
    nextLevel: "B2",
    missionPool: [
      "b1-startup-pitch",
      "b1-housing-negotiation",
      "b1-media-interview",
      "b1-team-conflict-mediation",
      "b1-bureaucracy-marathon",
      "b1-community-event",
      "b1-final-b2-bridge",
    ],
    requiredMissionIds: [
      "b1-startup-pitch",
      "b1-housing-negotiation",
      "b1-media-interview",
      "b1-final-b2-bridge",
    ],
    minCompletedMissions: 5,
    minOptionalMissions: 1,
    skillThresholds: [
      { skillKey: "vocab_core", minPoints: 640 },
      { skillKey: "grammar_syntax", minPoints: 500 },
      { skillKey: "listening_inference", minPoints: 360 },
      { skillKey: "speaking_fluency", minPoints: 380 },
      { skillKey: "pragmatics", minPoints: 320 },
      { skillKey: "task_completion", minPoints: 420 },
      { skillKey: "pronunciation", minPoints: 240 },
    ],
    sessionMinimums: { bronze: 60, silver: 42, gold: 20, minutes: 2000, activeDays: 40 },
    finalCheckpointMissionId: "b1-final-b2-bridge",
  },
  {
    level: "B2",
    missionPool: [],
    requiredMissionIds: [],
    minCompletedMissions: 0,
    minOptionalMissions: 0,
    skillThresholds: [],
    sessionMinimums: { bronze: 0, silver: 0, gold: 0, minutes: 0, activeDays: 0 },
  },
];

/**
 * Maps mission IDs → SRS card tags for topic-matched Bronze deck.
 * Single source of truth — no hardcoded maps in UI components.
 */
export const MISSION_CARD_TAGS: Record<string, string[]> = {
  "a1-flat-hunt-48h": ["home", "casa"],
  "a1-dinner-inlaws": ["food", "cibo-bevande", "ristorante", "famiglia"],
  "a1-last-train": ["travel", "trasporti", "viaggi"],
  "a1-workweek-milan": ["work", "lavoro"],
  "a1-shopping-rush": ["shopping", "fare-la-spesa", "shopping-comparativi"],
  "a1-midnight-pharmacy": ["health", "salute", "dal-dottore", "corpo"],
  "a1-social-circle": ["social", "presentarsi", "emozioni", "emotions"],
  "a1-final-day-test": ["routine", "routine-quotidiana"],
  "a2-roommate-reset": ["home", "casa", "opinioni"],
  "a2-customer-support-call": ["tech", "tecnologia", "bureaucracy"],
  "a2-family-visit-plan": ["famiglia", "fare-piani", "travel"],
  "a2-neighborhood-committee": ["social", "opinioni", "home"],
  "a2-travel-disruption-chain": ["travel", "trasporti", "viaggi"],
  "a2-health-followup": ["health", "salute", "dal-dottore"],
  "a2-final-city-week": ["routine", "routine-quotidiana", "social"],
  "b1-startup-pitch": ["work", "lavoro", "tech", "tecnologia"],
  "b1-housing-negotiation": ["home", "casa", "finance"],
  "b1-media-interview": ["media", "media-notizie", "opinioni"],
  "b1-team-conflict-mediation": ["work", "lavoro", "emotions", "emozioni"],
  "b1-bureaucracy-marathon": ["bureaucracy", "email-formali"],
  "b1-community-event": ["social", "vestiti", "shopping"],
  "b1-final-b2-bridge": ["connettivi", "congiuntivo-presente", "argomentare"],
};
