"use client";

import { useEffect, useMemo } from "react";
import { useQuery } from "convex/react";
import { api } from "../../../../convex/_generated/api";
import { useParams, useSearchParams } from "next/navigation";
import { useRouter } from "next/navigation";
import { ArrowLeft, Loader2 } from "lucide-react";
import Link from "next/link";
import type { Exercise, ExerciseMode } from "@/lib/exerciseTypes";
import { MODE_TYPES } from "@/lib/exerciseTypes";
import ExerciseFlow from "@/components/exercises/ExerciseFlow";
import ModeSelector from "@/components/ModeSelector";
import { useState } from "react";

const MODE_LABELS: Record<ExerciseMode, string> = {
  quick: "Bronze",
  standard: "Silver",
  deep: "Gold",
};

export default function SessionPage() {
  const router = useRouter();
  const params = useParams();
  const searchParams = useSearchParams();
  const dateParam = params.date as string;
  const modeParam = searchParams.get("mode") as ExerciseMode | null;

  const [selectedMode, setSelectedMode] = useState<ExerciseMode | null>(
    modeParam,
  );

  const allExercises = useQuery(api.exercises.getByDate, { date: dateParam });
  const modeCounts = useQuery(api.sessions.getModeCounts);
  const dueCards = useQuery(api.cards.getDue, { limit: 200 });

  const inferredTopicTag = useMemo(() => {
    if (!allExercises || allExercises.length === 0) return "";
    const bag: string[] = [];
    for (const ex of allExercises as Exercise[]) {
      if (ex.skillId) bag.push(ex.skillId);
      if (ex.type === "conversation") {
        const c = ex.content as { scenario?: string; target_phrases?: string[] };
        if (c?.scenario) bag.push(c.scenario);
        if (Array.isArray(c?.target_phrases)) bag.push(c.target_phrases.join(" "));
      }
      if (ex.type === "srs") {
        const c = ex.content as { front?: string; back?: string };
        if (c?.front) bag.push(c.front);
        if (c?.back) bag.push(c.back);
      }
    }
    const hay = bag.join(" ").toLowerCase();
    const tagRules: Array<{ tag: string; words: string[] }> = [
      { tag: "home", words: ["casa", "appartamento", "quartiere", "camera", "soggiorno"] },
      { tag: "food", words: ["ristorante", "cibo", "piatto", "mangiare", "cucina"] },
      { tag: "travel", words: ["viaggio", "treno", "vacanza", "hotel", "aeroporto"] },
      { tag: "work", words: ["lavoro", "ufficio", "riunione", "progetto"] },
      { tag: "sport", words: ["sport", "allenamento", "partita", "campione"] },
      { tag: "fitness", words: ["palestra", "allenarsi", "stretching", "benessere"] },
      { tag: "tech", words: ["tecnologia", "software", "codice", "app"] },
      { tag: "routine", words: ["giornata", "mattina", "abitudine", "quotidiana"] },
    ];
    let bestTag = "";
    let bestScore = 0;
    for (const rule of tagRules) {
      const score = rule.words.reduce(
        (acc, w) => (hay.includes(w) ? acc + 1 : acc),
        0,
      );
      if (score > bestScore) {
        bestScore = score;
        bestTag = rule.tag;
      }
    }
    return bestTag;
  }, [allExercises]);

  // Count exercises per type (for mode selector)
  const exerciseCounts = useMemo(() => {
    if (!allExercises) return {};
    const counts: Record<string, number> = {};
    for (const ex of allExercises) {
      counts[ex.type] = (counts[ex.type] ?? 0) + 1;
    }
    // Bronze must use the same SRS queue as /practice.
    if (dueCards) {
      counts.srs = inferredTopicTag
        ? dueCards.filter((c) => c.tag === inferredTopicTag).length
        : dueCards.length;
    }
    return counts;
  }, [allExercises, dueCards, inferredTopicTag]);

  useEffect(() => {
    if (selectedMode !== "quick") return;
    const p = new URLSearchParams({
      from: "session",
      mode: "bronze",
      date: dateParam,
    });
    if (inferredTopicTag) p.set("tag", inferredTopicTag);
    router.push(`/practice?${p.toString()}`);
  }, [dateParam, inferredTopicTag, router, selectedMode]);

  // Filter exercises by mode
  const modeExercises = useMemo(() => {
    if (!allExercises || !selectedMode) return [];
    const allowedTypes = new Set(MODE_TYPES[selectedMode]);
    return (allExercises as Exercise[])
      .filter((ex) => allowedTypes.has(ex.type as Exercise["type"]))
      .sort((a, b) => a.order - b.order);
  }, [allExercises, selectedMode]);

  // Loading
  if (allExercises === undefined) {
    return (
      <main className="min-h-screen flex items-center justify-center">
        <Loader2 size={32} className="text-accent animate-spin" />
      </main>
    );
  }

  // No exercises for this date
  if (allExercises.length === 0) {
    return (
      <main className="min-h-screen flex flex-col items-center justify-center gap-4 px-4">
        <p className="text-white/50">No exercises for {dateParam}</p>
        <p className="text-xs text-white/30">
          Exercises are generated by the Sunday batch or nightly patch.
        </p>
        <Link
          href="/"
          className="px-4 py-2 bg-accent rounded-xl text-sm hover:bg-accent/80 transition"
        >
          Back to Home
        </Link>
      </main>
    );
  }

  return (
    <main className="min-h-screen flex flex-col max-w-lg mx-auto pb-16">
      {/* Header */}
      <div className="flex items-center gap-3 px-4 py-3 border-b border-white/5 bg-card/50 backdrop-blur sticky top-0 z-10">
        <Link
          href="/"
          className="p-2 -ml-2 rounded-lg hover:bg-white/5 transition text-white/50 hover:text-white"
        >
          <ArrowLeft size={20} />
        </Link>
        <div className="flex-1 min-w-0">
          <h1 className="text-sm font-semibold">
            {selectedMode
              ? `${MODE_LABELS[selectedMode]} Session`
              : "Choose Tier"}
          </h1>
          <p className="text-xs text-white/30">{dateParam}</p>
        </div>
        {selectedMode && (
          <button
            onClick={() => setSelectedMode(null)}
            className="text-xs text-white/40 hover:text-white/60 transition"
          >
            Change mode
          </button>
        )}
      </div>

      {/* Mode selection or exercise flow */}
      {!selectedMode ? (
        <div className="px-4 py-6">
          <ModeSelector
            exerciseCounts={exerciseCounts}
            onSelect={setSelectedMode}
            sessionCounts={modeCounts ?? undefined}
          />
        </div>
      ) : selectedMode === "quick" ? (
        <div className="flex-1 flex flex-col items-center justify-center gap-3 px-4">
          <Loader2 size={24} className="text-accent animate-spin" />
          <p className="text-sm text-white/60">
            Opening Bronze SRS practice...
          </p>
        </div>
      ) : modeExercises.length === 0 ? (
        <div className="flex-1 flex flex-col items-center justify-center gap-4 px-4">
          <p className="text-white/50">
            No {MODE_LABELS[selectedMode]} exercises available
          </p>
          <button
            onClick={() => setSelectedMode(null)}
            className="px-4 py-2 bg-card rounded-xl border border-white/10 text-sm"
          >
            Choose different mode
          </button>
        </div>
      ) : (
        <ExerciseFlow
          exercises={modeExercises}
          mode={selectedMode}
          date={dateParam}
        />
      )}
    </main>
  );
}
